-- This file does not include postal code insert
--     1. postal_code insert
--     2. house hold data
-- Insert 100 household data
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('xhzkzad.sckkst@outlook.com','16627', 56011,'mobile home',68,NULL);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('ahqejl.csewbslre@outlook.com','17271', 96670,'condominium',72,73);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('fryjjhrez.gnltrdvumm@yahoo.com','83525', 44751,'mobile home',66,79);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('ndpipmp.bjkjk@gmail.com','38614', 22034,'townhome',71,80);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('rhwgp.bhvpfe@outlook.com','75951', 30352,'mobile home',71,74);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('vlcojiy.fwdjtczp@yahoo.com','23922', 83086,'apartment',73,71);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('vsgbgdl.tgftnz@gmail.com','98382', 81491,'house',73,80);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('dhhilddh.yudnpois@yahoo.com','15730', 62596,'apartment',75,NULL);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('wvakphra.qdrgftpkk@outlook.com','27217', 37282,'condominium',NULL,NULL);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('asjpka.rcklxq@outlook.com','65784', 76499,'house',NULL,NULL);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('pytpnqms.dtsnein@outlook.com','98953', 50374,'house',74,76);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('wnegrv.calkded@yahoo.com','28442', 93969,'townhome',69,80);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('cpixuxabd.qpdbx@gmail.com','4338', 46770,'condominium',72,79);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('eokjewvo.rolhepl@hotmail.com','96728', 55876,'condominium',71,79);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('mktxyyfbjl.kbqhrkxej@gmail.com','11499', 32031,'apartment',73,NULL);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('zxdphvm.bnflhn@hotmail.com','56080', 51119,'townhome',67,74);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('tmfcqvwei.eccrlwui@yahoo.com','29734', 82367,'mobile home',NULL,NULL);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('ovgjn.pngew@outlook.com','22714', 75440,'house',73,74);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('grmngou.wrgrbsbmey@hotmail.com','18461', 5322,'townhome',NULL,NULL);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('itdzt.kjrhulh@outlook.com','94562', 77501,'mobile home',68,79);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('unzqoq.fjhopwiee@outlook.com','54466', 13567,'condominium',74,70);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('khvxmd.lanqe@gmail.com','48867', 11432,'mobile home',67,NULL);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('urstm.lyrgcnn@gmail.com','62446', 11980,'townhome',65,79);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('hjypic.agcbb@outlook.com','97366', 54032,'condominium',72,74);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('fqeshxgx.llblpd@gmail.com','84530', 58028,'house',NULL,NULL);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('spsmxyozhq.qywtidufjz@gmail.com','28043', 41447,'house',74,70);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('mdreacz.ejbkihgmkw@outlook.com','81226', 45457,'condominium',68,78);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('zzzdt.zaxsxftzxv@gmail.com','67058', 42239,'mobile home',NULL,NULL);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('erlmfpw.gvmypognpu@hotmail.com','20580', 54896,'townhome',71,NULL);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('ccxezue.wuxtawu@gmail.com','13834', 67246,'apartment',70,73);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('kcovojowh.wjybftve@gmail.com','75680', 59492,'mobile home',66,70);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('pyetbtyxu.bnsgiajmkz@hotmail.com','50321', 30865,'house',65,80);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('giodplp.hvmwyh@outlook.com','19179', 72628,'condominium',NULL,NULL);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('xcwfvut.kamua@gmail.com','28409', 87968,'townhome',68,78);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('iolqf.bfwtgsze@yahoo.com','79841', 44738,'condominium',74,76);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('aqtluaij.tpcqmk@outlook.com','24872', 90477,'apartment',66,NULL);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('uwvdpz.tvmjsi@outlook.com','72033', 74355,'house',NULL,NULL);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('yybzp.ohldcewgzs@outlook.com','95959', 6237,'house',66,80);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('epjnhjif.pfbncwh@hotmail.com','21241', 48345,'house',75,76);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('nsarfibcoq.sttulj@outlook.com','52336', 49196,'apartment',67,76);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('djttpsh.nnizif@gmail.com','90421', 56138,'house',NULL,NULL);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('bgfruxt.bzxaqn@yahoo.com','29048', 94705,'house',75,77);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('pnlreotd.gycaxkvmvo@hotmail.com','22989', 34324,'condominium',65,NULL);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('srzwkfjyo.hgotns@gmail.com','66945', 18358,'house',69,80);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('ufnerjhy.lplqrstry@yahoo.com','57059', 66719,'apartment',75,76);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('klcnkuqwk.ufazrl@outlook.com','15233', 81405,'house',NULL,NULL);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('jorce.jcrvnderk@yahoo.com','32359', 13878,'apartment',68,76);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('pjnpi.tohfvsn@outlook.com','28055', 83495,'house',67,80);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('iyyol.glujl@gmail.com','71929', 25168,'condominium',NULL,NULL);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('bmfxvqf.dyewekj@outlook.com','33834', 54716,'house',71,NULL);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('smpwu.gibhncer@hotmail.com','92885', 67769,'house',68,77);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('dygzz.gqehriguo@hotmail.com','15379', 80596,'townhome',65,76);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('xzwstkiibr.clxbqwvvm@yahoo.com','67491', 48558,'mobile home',72,72);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('pywvpw.tbgml@outlook.com','88539', 36124,'mobile home',75,70);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('ptcmpco.jnqalia@outlook.com','82839', 1708,'mobile home',NULL,NULL);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('zwqthuc.xhrjzxwr@hotmail.com','75462', 44470,'apartment',73,71);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('uralvthzi.jyjhohvvdg@gmail.com','64840', 32485,'mobile home',69,NULL);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('sjosrgks.qbdwuqmjl@outlook.com','97405', 42009,'townhome',65,71);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('ndmqxhli.wlaypuawv@gmail.com','70522', 19529,'condominium',68,79);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('itewtwyzw.qdvpfx@outlook.com','62058', 56809,'house',75,78);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('mmwraelwm.uvjrsp@outlook.com','42323', 92017,'house',71,73);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('zttqvvo.nxcxor@outlook.com','86434', 12897,'condominium',70,79);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('hvbac.jzcla@hotmail.com','8863', 37458,'mobile home',65,76);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('tcgjbbv.tybrggdl@gmail.com','25028', 41322,'mobile home',73,NULL);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('gulsthcn.nhabzdc@yahoo.com','44040', 43407,'house',NULL,NULL);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('jkmoj.anlzli@gmail.com','90607', 41888,'townhome',72,78);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('bkbio.yghhi@hotmail.com','27892', 24608,'condominium',66,74);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('mxqfsbzvhq.pmdfz@outlook.com','39328', 19256,'house',71,76);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('nxabsvdx.lseiew@hotmail.com','28366', 43410,'townhome',72,74);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('dbbxdtzqn.qioarzw@hotmail.com','83276', 46316,'house',67,76);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('dwszhdtxk.hcpjjbcc@gmail.com','11819', 36132,'condominium',65,NULL);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('eynkd.ounorracj@outlook.com','52738', 65846,'mobile home',70,80);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('mgpbl.jfkwks@outlook.com','4743', 3248,'townhome',NULL,NULL);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('vnqfmfpja.lodgygnunm@outlook.com','20624', 39581,'house',67,76);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('kpcfrihokc.rdaqylsjlm@gmail.com','45140', 64325,'townhome',66,80);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('qimlly.xxnejproek@hotmail.com','75189', 71464,'house',73,70);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('opqsbcms.unwlrcpka@hotmail.com','85317', 17877,'condominium',70,80);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('agsciy.yorxv@outlook.com','68450', 28741,'apartment',69,NULL);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('znnjjutr.gnnmt@yahoo.com','47840', 67228,'townhome',74,80);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('zplewtkzdi.hhanyrxh@hotmail.com','57059', 69499,'townhome',68,74);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('tclplxspg.ertff@gmail.com','31772', 58347,'apartment',NULL,NULL);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('nvxofsr.hcrpv@yahoo.com','48265', 35659,'townhome',NULL,NULL);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('fgaenbx.tirfmblwmb@outlook.com','37243', 90415,'mobile home',72,78);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('fbjnjj.jnhcfp@outlook.com','99319', 83521,'house',68,73);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('ypghd.ocqvp@yahoo.com','44082', 27651,'apartment',73,NULL);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('wrebxlyza.zilvomjtr@yahoo.com','73458', 20973,'condominium',67,73);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('edbsgqp.lsnofunj@hotmail.com','15723', 49612,'condominium',72,80);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('fntafhzqe.uhexacvsog@hotmail.com','30133', 76811,'townhome',74,71);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('gsbyss.jlcghlrgtv@gmail.com','4736', 64113,'apartment',NULL,NULL);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('lofdibmw.yhhrztbqcd@hotmail.com','3452', 87797,'apartment',66,78);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('sbipn.kuqoihyvun@yahoo.com','33445', 20829,'apartment',NULL,NULL);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('kyqzwjq.qgtxlhlz@outlook.com','76716', 44450,'townhome',67,NULL);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('wattdc.kpwmzbip@yahoo.com','21606', 34629,'house',73,70);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('qasge.vkwhx@yahoo.com','17815', 59857,'mobile home',75,80);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('zilqrs.onvmnl@gmail.com','27559', 50800,'townhome',75,70);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('diztbfzr.vqbzb@gmail.com','49548', 20688,'condominium',68,74);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('dmemwafc.mxoacset@yahoo.com','21401', 56179,'townhome',NULL,NULL);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('dozaxk.snrqcadfr@hotmail.com','73737', 94490,'apartment',74,75);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('bwcrbvt.pmsfqbwo@hotmail.com','31008', 44197,'house',75,NULL);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('squsr.ariepax@outlook.com','32160', 78784,'mobile home',NULL,NULL);

--     3. UtilityType
INSERT INTO UtilityType (Email, UtilityType) values ('xhzkzad.sckkst@outlook.com','steam');
INSERT INTO UtilityType (Email, UtilityType) values ('ahqejl.csewbslre@outlook.com','steam');
INSERT INTO UtilityType (Email, UtilityType) values ('fryjjhrez.gnltrdvumm@yahoo.com','gas');
INSERT INTO UtilityType (Email, UtilityType) values ('ndpipmp.bjkjk@gmail.com','gas');
INSERT INTO UtilityType (Email, UtilityType) values ('rhwgp.bhvpfe@outlook.com','gas');
INSERT INTO UtilityType (Email, UtilityType) values ('vlcojiy.fwdjtczp@yahoo.com','fuel oil');
INSERT INTO UtilityType (Email, UtilityType) values ('vsgbgdl.tgftnz@gmail.com','electric');
INSERT INTO UtilityType (Email, UtilityType) values ('dhhilddh.yudnpois@yahoo.com','gas');
INSERT INTO UtilityType (Email, UtilityType) values ('wvakphra.qdrgftpkk@outlook.com','off-the-grid');
INSERT INTO UtilityType (Email, UtilityType) values ('asjpka.rcklxq@outlook.com','off-the-grid');
INSERT INTO UtilityType (Email, UtilityType) values ('pytpnqms.dtsnein@outlook.com','electric');
INSERT INTO UtilityType (Email, UtilityType) values ('wnegrv.calkded@yahoo.com','gas');
INSERT INTO UtilityType (Email, UtilityType) values ('cpixuxabd.qpdbx@gmail.com','steam');
INSERT INTO UtilityType (Email, UtilityType) values ('eokjewvo.rolhepl@hotmail.com','electric');
INSERT INTO UtilityType (Email, UtilityType) values ('mktxyyfbjl.kbqhrkxej@gmail.com','electric');
INSERT INTO UtilityType (Email, UtilityType) values ('zxdphvm.bnflhn@hotmail.com','electric');
INSERT INTO UtilityType (Email, UtilityType) values ('tmfcqvwei.eccrlwui@yahoo.com','off-the-grid');
INSERT INTO UtilityType (Email, UtilityType) values ('ovgjn.pngew@outlook.com','electric');
INSERT INTO UtilityType (Email, UtilityType) values ('grmngou.wrgrbsbmey@hotmail.com','off-the-grid');
INSERT INTO UtilityType (Email, UtilityType) values ('itdzt.kjrhulh@outlook.com','gas');
INSERT INTO UtilityType (Email, UtilityType) values ('unzqoq.fjhopwiee@outlook.com','electric');
INSERT INTO UtilityType (Email, UtilityType) values ('khvxmd.lanqe@gmail.com','gas');
INSERT INTO UtilityType (Email, UtilityType) values ('urstm.lyrgcnn@gmail.com','electric');
INSERT INTO UtilityType (Email, UtilityType) values ('hjypic.agcbb@outlook.com','gas');
INSERT INTO UtilityType (Email, UtilityType) values ('fqeshxgx.llblpd@gmail.com','off-the-grid');
INSERT INTO UtilityType (Email, UtilityType) values ('spsmxyozhq.qywtidufjz@gmail.com','gas');
INSERT INTO UtilityType (Email, UtilityType) values ('mdreacz.ejbkihgmkw@outlook.com','electric');
INSERT INTO UtilityType (Email, UtilityType) values ('zzzdt.zaxsxftzxv@gmail.com','off-the-grid');
INSERT INTO UtilityType (Email, UtilityType) values ('erlmfpw.gvmypognpu@hotmail.com','steam');
INSERT INTO UtilityType (Email, UtilityType) values ('ccxezue.wuxtawu@gmail.com','fuel oil');
INSERT INTO UtilityType (Email, UtilityType) values ('kcovojowh.wjybftve@gmail.com','electric');
INSERT INTO UtilityType (Email, UtilityType) values ('pyetbtyxu.bnsgiajmkz@hotmail.com','fuel oil');
INSERT INTO UtilityType (Email, UtilityType) values ('giodplp.hvmwyh@outlook.com','off-the-grid');
INSERT INTO UtilityType (Email, UtilityType) values ('xcwfvut.kamua@gmail.com','steam');
INSERT INTO UtilityType (Email, UtilityType) values ('iolqf.bfwtgsze@yahoo.com','gas');
INSERT INTO UtilityType (Email, UtilityType) values ('aqtluaij.tpcqmk@outlook.com','gas');
INSERT INTO UtilityType (Email, UtilityType) values ('uwvdpz.tvmjsi@outlook.com','off-the-grid');
INSERT INTO UtilityType (Email, UtilityType) values ('yybzp.ohldcewgzs@outlook.com','steam');
INSERT INTO UtilityType (Email, UtilityType) values ('epjnhjif.pfbncwh@hotmail.com','electric');
INSERT INTO UtilityType (Email, UtilityType) values ('nsarfibcoq.sttulj@outlook.com','fuel oil');
INSERT INTO UtilityType (Email, UtilityType) values ('djttpsh.nnizif@gmail.com','off-the-grid');
INSERT INTO UtilityType (Email, UtilityType) values ('bgfruxt.bzxaqn@yahoo.com','electric');
INSERT INTO UtilityType (Email, UtilityType) values ('pnlreotd.gycaxkvmvo@hotmail.com','gas');
INSERT INTO UtilityType (Email, UtilityType) values ('srzwkfjyo.hgotns@gmail.com','fuel oil');
INSERT INTO UtilityType (Email, UtilityType) values ('ufnerjhy.lplqrstry@yahoo.com','steam');
INSERT INTO UtilityType (Email, UtilityType) values ('klcnkuqwk.ufazrl@outlook.com','off-the-grid');
INSERT INTO UtilityType (Email, UtilityType) values ('jorce.jcrvnderk@yahoo.com','gas');
INSERT INTO UtilityType (Email, UtilityType) values ('pjnpi.tohfvsn@outlook.com','fuel oil');
INSERT INTO UtilityType (Email, UtilityType) values ('iyyol.glujl@gmail.com','off-the-grid');
INSERT INTO UtilityType (Email, UtilityType) values ('bmfxvqf.dyewekj@outlook.com','electric');
INSERT INTO UtilityType (Email, UtilityType) values ('smpwu.gibhncer@hotmail.com','steam');
INSERT INTO UtilityType (Email, UtilityType) values ('dygzz.gqehriguo@hotmail.com','fuel oil');
INSERT INTO UtilityType (Email, UtilityType) values ('xzwstkiibr.clxbqwvvm@yahoo.com','steam');
INSERT INTO UtilityType (Email, UtilityType) values ('pywvpw.tbgml@outlook.com','electric');
INSERT INTO UtilityType (Email, UtilityType) values ('ptcmpco.jnqalia@outlook.com','off-the-grid');
INSERT INTO UtilityType (Email, UtilityType) values ('zwqthuc.xhrjzxwr@hotmail.com','electric');
INSERT INTO UtilityType (Email, UtilityType) values ('uralvthzi.jyjhohvvdg@gmail.com','gas');
INSERT INTO UtilityType (Email, UtilityType) values ('sjosrgks.qbdwuqmjl@outlook.com','gas');
INSERT INTO UtilityType (Email, UtilityType) values ('ndmqxhli.wlaypuawv@gmail.com','electric');
INSERT INTO UtilityType (Email, UtilityType) values ('itewtwyzw.qdvpfx@outlook.com','steam');
INSERT INTO UtilityType (Email, UtilityType) values ('mmwraelwm.uvjrsp@outlook.com','electric');
INSERT INTO UtilityType (Email, UtilityType) values ('zttqvvo.nxcxor@outlook.com','electric');
INSERT INTO UtilityType (Email, UtilityType) values ('hvbac.jzcla@hotmail.com','steam');
INSERT INTO UtilityType (Email, UtilityType) values ('tcgjbbv.tybrggdl@gmail.com','fuel oil');
INSERT INTO UtilityType (Email, UtilityType) values ('gulsthcn.nhabzdc@yahoo.com','off-the-grid');
INSERT INTO UtilityType (Email, UtilityType) values ('jkmoj.anlzli@gmail.com','fuel oil');
INSERT INTO UtilityType (Email, UtilityType) values ('bkbio.yghhi@hotmail.com','electric');
INSERT INTO UtilityType (Email, UtilityType) values ('mxqfsbzvhq.pmdfz@outlook.com','steam');
INSERT INTO UtilityType (Email, UtilityType) values ('nxabsvdx.lseiew@hotmail.com','gas');
INSERT INTO UtilityType (Email, UtilityType) values ('dbbxdtzqn.qioarzw@hotmail.com','steam');
INSERT INTO UtilityType (Email, UtilityType) values ('dwszhdtxk.hcpjjbcc@gmail.com','gas');
INSERT INTO UtilityType (Email, UtilityType) values ('eynkd.ounorracj@outlook.com','steam');
INSERT INTO UtilityType (Email, UtilityType) values ('mgpbl.jfkwks@outlook.com','off-the-grid');
INSERT INTO UtilityType (Email, UtilityType) values ('vnqfmfpja.lodgygnunm@outlook.com','steam');
INSERT INTO UtilityType (Email, UtilityType) values ('kpcfrihokc.rdaqylsjlm@gmail.com','steam');
INSERT INTO UtilityType (Email, UtilityType) values ('qimlly.xxnejproek@hotmail.com','gas');
INSERT INTO UtilityType (Email, UtilityType) values ('opqsbcms.unwlrcpka@hotmail.com','electric');
INSERT INTO UtilityType (Email, UtilityType) values ('agsciy.yorxv@outlook.com','gas');
INSERT INTO UtilityType (Email, UtilityType) values ('znnjjutr.gnnmt@yahoo.com','steam');
INSERT INTO UtilityType (Email, UtilityType) values ('zplewtkzdi.hhanyrxh@hotmail.com','electric');
INSERT INTO UtilityType (Email, UtilityType) values ('tclplxspg.ertff@gmail.com','off-the-grid');
INSERT INTO UtilityType (Email, UtilityType) values ('nvxofsr.hcrpv@yahoo.com','off-the-grid');
INSERT INTO UtilityType (Email, UtilityType) values ('fgaenbx.tirfmblwmb@outlook.com','steam');
INSERT INTO UtilityType (Email, UtilityType) values ('fbjnjj.jnhcfp@outlook.com','steam');
INSERT INTO UtilityType (Email, UtilityType) values ('ypghd.ocqvp@yahoo.com','fuel oil');
INSERT INTO UtilityType (Email, UtilityType) values ('wrebxlyza.zilvomjtr@yahoo.com','steam');
INSERT INTO UtilityType (Email, UtilityType) values ('edbsgqp.lsnofunj@hotmail.com','fuel oil');
INSERT INTO UtilityType (Email, UtilityType) values ('fntafhzqe.uhexacvsog@hotmail.com','steam');
INSERT INTO UtilityType (Email, UtilityType) values ('gsbyss.jlcghlrgtv@gmail.com','off-the-grid');
INSERT INTO UtilityType (Email, UtilityType) values ('lofdibmw.yhhrztbqcd@hotmail.com','gas');
INSERT INTO UtilityType (Email, UtilityType) values ('sbipn.kuqoihyvun@yahoo.com','off-the-grid');
INSERT INTO UtilityType (Email, UtilityType) values ('kyqzwjq.qgtxlhlz@outlook.com','gas');
INSERT INTO UtilityType (Email, UtilityType) values ('wattdc.kpwmzbip@yahoo.com','steam');
INSERT INTO UtilityType (Email, UtilityType) values ('qasge.vkwhx@yahoo.com','steam');
INSERT INTO UtilityType (Email, UtilityType) values ('zilqrs.onvmnl@gmail.com','gas');
INSERT INTO UtilityType (Email, UtilityType) values ('diztbfzr.vqbzb@gmail.com','electric');
INSERT INTO UtilityType (Email, UtilityType) values ('dmemwafc.mxoacset@yahoo.com','off-the-grid');
INSERT INTO UtilityType (Email, UtilityType) values ('dozaxk.snrqcadfr@hotmail.com','steam');
INSERT INTO UtilityType (Email, UtilityType) values ('bwcrbvt.pmsfqbwo@hotmail.com','steam');
INSERT INTO UtilityType (Email, UtilityType) values ('squsr.ariepax@outlook.com','off-the-grid');

--     4. manufacturer
INSERT INTO Manufacturer (Name) values ('Rheem');
INSERT INTO Manufacturer (Name) values ('Dimplex');
INSERT INTO Manufacturer (Name) values ('Carrier');
INSERT INTO Manufacturer (Name) values ('Mitsubishi Electric');
INSERT INTO Manufacturer (Name) values ('Bradford White');
INSERT INTO Manufacturer (Name) values ('Lasko');
INSERT INTO Manufacturer (Name) values ('Trane');
INSERT INTO Manufacturer (Name) values ('Fujitsu');
INSERT INTO Manufacturer (Name) values ('AO Smith');
INSERT INTO Manufacturer (Name) values ('DeLonghi');
INSERT INTO Manufacturer (Name) values ('Lennox');
INSERT INTO Manufacturer (Name) values ('LG');
INSERT INTO Manufacturer (Name) values ('Whirlpool');
INSERT INTO Manufacturer (Name) values ('Dr. Infrared');
INSERT INTO Manufacturer (Name) values ('Goodman');
INSERT INTO Manufacturer (Name) values ('Daikin');
INSERT INTO Manufacturer (Name) values ('Rinnai');
INSERT INTO Manufacturer (Name) values ('Honeywell');
--     5. PowerGenerator
INSERT INTO PowerGenerator (Email, PowerGeneratorId, PowerGenerationType, AverageKWH, StorageKWh) values ('xhzkzad.sckkst@outlook.com',1, 'wind', 925,864);
INSERT INTO PowerGenerator (Email, PowerGeneratorId, PowerGenerationType, AverageKWH, StorageKWh) values ('ahqejl.csewbslre@outlook.com',1, 'solar-electric', 900,802);
INSERT INTO PowerGenerator (Email, PowerGeneratorId, PowerGenerationType, AverageKWH, StorageKWh) values ('fryjjhrez.gnltrdvumm@yahoo.com',1, 'wind', 984,628);
INSERT INTO PowerGenerator (Email, PowerGeneratorId, PowerGenerationType, AverageKWH, StorageKWh) values ('ndpipmp.bjkjk@gmail.com',1, 'wind', 902,718);
INSERT INTO PowerGenerator (Email, PowerGeneratorId, PowerGenerationType, AverageKWH, StorageKWh) values ('rhwgp.bhvpfe@outlook.com',1, 'wind', 786,727);
INSERT INTO PowerGenerator (Email, PowerGeneratorId, PowerGenerationType, AverageKWH, StorageKWh) values ('vlcojiy.fwdjtczp@yahoo.com',1, 'solar-electric', 731,535);
INSERT INTO PowerGenerator (Email, PowerGeneratorId, PowerGenerationType, AverageKWH, StorageKWh) values ('vsgbgdl.tgftnz@gmail.com',1, 'solar-electric', 891,716);
INSERT INTO PowerGenerator (Email, PowerGeneratorId, PowerGenerationType, AverageKWH, StorageKWh) values ('dhhilddh.yudnpois@yahoo.com',1, 'wind', 981,506);
INSERT INTO PowerGenerator (Email, PowerGeneratorId, PowerGenerationType, AverageKWH, StorageKWh) values ('pytpnqms.dtsnein@outlook.com',1, 'solar-electric', 511,740);
INSERT INTO PowerGenerator (Email, PowerGeneratorId, PowerGenerationType, AverageKWH, StorageKWh) values ('wnegrv.calkded@yahoo.com',1, 'wind', 643,925);
INSERT INTO PowerGenerator (Email, PowerGeneratorId, PowerGenerationType, AverageKWH, StorageKWh) values ('cpixuxabd.qpdbx@gmail.com',1, 'wind', 792,906);
INSERT INTO PowerGenerator (Email, PowerGeneratorId, PowerGenerationType, AverageKWH, StorageKWh) values ('eokjewvo.rolhepl@hotmail.com',1, 'solar-electric', 657,509);
INSERT INTO PowerGenerator (Email, PowerGeneratorId, PowerGenerationType, AverageKWH, StorageKWh) values ('mktxyyfbjl.kbqhrkxej@gmail.com',1, 'solar-electric', 531,880);
INSERT INTO PowerGenerator (Email, PowerGeneratorId, PowerGenerationType, AverageKWH, StorageKWh) values ('zxdphvm.bnflhn@hotmail.com',1, 'solar-electric', 870,910);
INSERT INTO PowerGenerator (Email, PowerGeneratorId, PowerGenerationType, AverageKWH, StorageKWh) values ('ovgjn.pngew@outlook.com',1, 'solar-electric', 798,592);
INSERT INTO PowerGenerator (Email, PowerGeneratorId, PowerGenerationType, AverageKWH, StorageKWh) values ('itdzt.kjrhulh@outlook.com',1, 'solar-electric', 640,824);
INSERT INTO PowerGenerator (Email, PowerGeneratorId, PowerGenerationType, AverageKWH, StorageKWh) values ('unzqoq.fjhopwiee@outlook.com',1, 'solar-electric', 891,831);
INSERT INTO PowerGenerator (Email, PowerGeneratorId, PowerGenerationType, AverageKWH, StorageKWh) values ('khvxmd.lanqe@gmail.com',1, 'wind', 840,689);
INSERT INTO PowerGenerator (Email, PowerGeneratorId, PowerGenerationType, AverageKWH, StorageKWh) values ('urstm.lyrgcnn@gmail.com',1, 'solar-electric', 947,734);
INSERT INTO PowerGenerator (Email, PowerGeneratorId, PowerGenerationType, AverageKWH, StorageKWh) values ('hjypic.agcbb@outlook.com',1, 'wind', 523,628);
INSERT INTO PowerGenerator (Email, PowerGeneratorId, PowerGenerationType, AverageKWH, StorageKWh) values ('spsmxyozhq.qywtidufjz@gmail.com',1, 'wind', 677,637);
INSERT INTO PowerGenerator (Email, PowerGeneratorId, PowerGenerationType, AverageKWH, StorageKWh) values ('mdreacz.ejbkihgmkw@outlook.com',1, 'solar-electric', 876,575);
INSERT INTO PowerGenerator (Email, PowerGeneratorId, PowerGenerationType, AverageKWH, StorageKWh) values ('erlmfpw.gvmypognpu@hotmail.com',1, 'solar-electric', 983,645);
INSERT INTO PowerGenerator (Email, PowerGeneratorId, PowerGenerationType, AverageKWH, StorageKWh) values ('ccxezue.wuxtawu@gmail.com',1, 'solar-electric', 524,759);
INSERT INTO PowerGenerator (Email, PowerGeneratorId, PowerGenerationType, AverageKWH, StorageKWh) values ('kcovojowh.wjybftve@gmail.com',1, 'solar-electric', 710,558);
INSERT INTO PowerGenerator (Email, PowerGeneratorId, PowerGenerationType, AverageKWH, StorageKWh) values ('pyetbtyxu.bnsgiajmkz@hotmail.com',1, 'wind', 836,889);
INSERT INTO PowerGenerator (Email, PowerGeneratorId, PowerGenerationType, AverageKWH, StorageKWh) values ('xcwfvut.kamua@gmail.com',1, 'solar-electric', 877,735);
INSERT INTO PowerGenerator (Email, PowerGeneratorId, PowerGenerationType, AverageKWH, StorageKWh) values ('iolqf.bfwtgsze@yahoo.com',1, 'solar-electric', 567,916);
INSERT INTO PowerGenerator (Email, PowerGeneratorId, PowerGenerationType, AverageKWH, StorageKWh) values ('aqtluaij.tpcqmk@outlook.com',1, 'solar-electric', 972,781);
INSERT INTO PowerGenerator (Email, PowerGeneratorId, PowerGenerationType, AverageKWH, StorageKWh) values ('yybzp.ohldcewgzs@outlook.com',1, 'wind', 689,598);
INSERT INTO PowerGenerator (Email, PowerGeneratorId, PowerGenerationType, AverageKWH, StorageKWh) values ('epjnhjif.pfbncwh@hotmail.com',1, 'wind', 883,619);
INSERT INTO PowerGenerator (Email, PowerGeneratorId, PowerGenerationType, AverageKWH, StorageKWh) values ('nsarfibcoq.sttulj@outlook.com',1, 'solar-electric', 601,844);
INSERT INTO PowerGenerator (Email, PowerGeneratorId, PowerGenerationType, AverageKWH, StorageKWh) values ('bgfruxt.bzxaqn@yahoo.com',1, 'solar-electric', 759,999);
INSERT INTO PowerGenerator (Email, PowerGeneratorId, PowerGenerationType, AverageKWH, StorageKWh) values ('pnlreotd.gycaxkvmvo@hotmail.com',1, 'wind', 720,513);
INSERT INTO PowerGenerator (Email, PowerGeneratorId, PowerGenerationType, AverageKWH, StorageKWh) values ('srzwkfjyo.hgotns@gmail.com',1, 'solar-electric', 846,803);
INSERT INTO PowerGenerator (Email, PowerGeneratorId, PowerGenerationType, AverageKWH, StorageKWh) values ('ufnerjhy.lplqrstry@yahoo.com',1, 'solar-electric', 544,679);
INSERT INTO PowerGenerator (Email, PowerGeneratorId, PowerGenerationType, AverageKWH, StorageKWh) values ('jorce.jcrvnderk@yahoo.com',1, 'wind', 956,519);
INSERT INTO PowerGenerator (Email, PowerGeneratorId, PowerGenerationType, AverageKWH, StorageKWh) values ('pjnpi.tohfvsn@outlook.com',1, 'solar-electric', 948,510);
INSERT INTO PowerGenerator (Email, PowerGeneratorId, PowerGenerationType, AverageKWH, StorageKWh) values ('bmfxvqf.dyewekj@outlook.com',1, 'solar-electric', 641,650);
INSERT INTO PowerGenerator (Email, PowerGeneratorId, PowerGenerationType, AverageKWH, StorageKWh) values ('smpwu.gibhncer@hotmail.com',1, 'solar-electric', 995,999);
INSERT INTO PowerGenerator (Email, PowerGeneratorId, PowerGenerationType, AverageKWH, StorageKWh) values ('dygzz.gqehriguo@hotmail.com',1, 'solar-electric', 612,793);
INSERT INTO PowerGenerator (Email, PowerGeneratorId, PowerGenerationType, AverageKWH, StorageKWh) values ('xzwstkiibr.clxbqwvvm@yahoo.com',1, 'wind', 661,805);
INSERT INTO PowerGenerator (Email, PowerGeneratorId, PowerGenerationType, AverageKWH, StorageKWh) values ('pywvpw.tbgml@outlook.com',1, 'solar-electric', 951,855);
INSERT INTO PowerGenerator (Email, PowerGeneratorId, PowerGenerationType, AverageKWH, StorageKWh) values ('zwqthuc.xhrjzxwr@hotmail.com',1, 'solar-electric', 599,980);
INSERT INTO PowerGenerator (Email, PowerGeneratorId, PowerGenerationType, AverageKWH, StorageKWh) values ('uralvthzi.jyjhohvvdg@gmail.com',1, 'wind', 704,606);
INSERT INTO PowerGenerator (Email, PowerGeneratorId, PowerGenerationType, AverageKWH, StorageKWh) values ('sjosrgks.qbdwuqmjl@outlook.com',1, 'solar-electric', 790,515);
INSERT INTO PowerGenerator (Email, PowerGeneratorId, PowerGenerationType, AverageKWH, StorageKWh) values ('ndmqxhli.wlaypuawv@gmail.com',1, 'solar-electric', 614,653);
INSERT INTO PowerGenerator (Email, PowerGeneratorId, PowerGenerationType, AverageKWH, StorageKWh) values ('itewtwyzw.qdvpfx@outlook.com',1, 'wind', 818,668);
INSERT INTO PowerGenerator (Email, PowerGeneratorId, PowerGenerationType, AverageKWH, StorageKWh) values ('mmwraelwm.uvjrsp@outlook.com',1, 'solar-electric', 553,704);
INSERT INTO PowerGenerator (Email, PowerGeneratorId, PowerGenerationType, AverageKWH, StorageKWh) values ('zttqvvo.nxcxor@outlook.com',1, 'solar-electric', 916,502);
INSERT INTO PowerGenerator (Email, PowerGeneratorId, PowerGenerationType, AverageKWH, StorageKWh) values ('hvbac.jzcla@hotmail.com',1, 'wind', 795,724);
INSERT INTO PowerGenerator (Email, PowerGeneratorId, PowerGenerationType, AverageKWH, StorageKWh) values ('tcgjbbv.tybrggdl@gmail.com',1, 'solar-electric', 781,763);
INSERT INTO PowerGenerator (Email, PowerGeneratorId, PowerGenerationType, AverageKWH, StorageKWh) values ('jkmoj.anlzli@gmail.com',1, 'solar-electric', 664,680);
INSERT INTO PowerGenerator (Email, PowerGeneratorId, PowerGenerationType, AverageKWH, StorageKWh) values ('bkbio.yghhi@hotmail.com',1, 'solar-electric', 715,664);
INSERT INTO PowerGenerator (Email, PowerGeneratorId, PowerGenerationType, AverageKWH, StorageKWh) values ('mxqfsbzvhq.pmdfz@outlook.com',1, 'wind', 785,638);
INSERT INTO PowerGenerator (Email, PowerGeneratorId, PowerGenerationType, AverageKWH, StorageKWh) values ('nxabsvdx.lseiew@hotmail.com',1, 'wind', 619,856);
INSERT INTO PowerGenerator (Email, PowerGeneratorId, PowerGenerationType, AverageKWH, StorageKWh) values ('dbbxdtzqn.qioarzw@hotmail.com',1, 'solar-electric', 979,605);
INSERT INTO PowerGenerator (Email, PowerGeneratorId, PowerGenerationType, AverageKWH, StorageKWh) values ('dwszhdtxk.hcpjjbcc@gmail.com',1, 'wind', 855,825);
INSERT INTO PowerGenerator (Email, PowerGeneratorId, PowerGenerationType, AverageKWH, StorageKWh) values ('eynkd.ounorracj@outlook.com',1, 'solar-electric', 833,755);
INSERT INTO PowerGenerator (Email, PowerGeneratorId, PowerGenerationType, AverageKWH, StorageKWh) values ('vnqfmfpja.lodgygnunm@outlook.com',1, 'wind', 658,833);
INSERT INTO PowerGenerator (Email, PowerGeneratorId, PowerGenerationType, AverageKWH, StorageKWh) values ('kpcfrihokc.rdaqylsjlm@gmail.com',1, 'solar-electric', 821,898);
INSERT INTO PowerGenerator (Email, PowerGeneratorId, PowerGenerationType, AverageKWH, StorageKWh) values ('qimlly.xxnejproek@hotmail.com',1, 'solar-electric', 915,749);
INSERT INTO PowerGenerator (Email, PowerGeneratorId, PowerGenerationType, AverageKWH, StorageKWh) values ('opqsbcms.unwlrcpka@hotmail.com',1, 'wind', 836,648);
INSERT INTO PowerGenerator (Email, PowerGeneratorId, PowerGenerationType, AverageKWH, StorageKWh) values ('agsciy.yorxv@outlook.com',1, 'wind', 697,847);
INSERT INTO PowerGenerator (Email, PowerGeneratorId, PowerGenerationType, AverageKWH, StorageKWh) values ('znnjjutr.gnnmt@yahoo.com',1, 'solar-electric', 802,511);
INSERT INTO PowerGenerator (Email, PowerGeneratorId, PowerGenerationType, AverageKWH, StorageKWh) values ('zplewtkzdi.hhanyrxh@hotmail.com',1, 'wind', 959,834);
INSERT INTO PowerGenerator (Email, PowerGeneratorId, PowerGenerationType, AverageKWH, StorageKWh) values ('fgaenbx.tirfmblwmb@outlook.com',1, 'solar-electric', 795,724);
INSERT INTO PowerGenerator (Email, PowerGeneratorId, PowerGenerationType, AverageKWH, StorageKWh) values ('fbjnjj.jnhcfp@outlook.com',1, 'solar-electric', 529,707);
INSERT INTO PowerGenerator (Email, PowerGeneratorId, PowerGenerationType, AverageKWH, StorageKWh) values ('ypghd.ocqvp@yahoo.com',1, 'solar-electric', 531,847);
INSERT INTO PowerGenerator (Email, PowerGeneratorId, PowerGenerationType, AverageKWH, StorageKWh) values ('wrebxlyza.zilvomjtr@yahoo.com',1, 'solar-electric', 747,580);
INSERT INTO PowerGenerator (Email, PowerGeneratorId, PowerGenerationType, AverageKWH, StorageKWh) values ('edbsgqp.lsnofunj@hotmail.com',1, 'wind', 780,651);
INSERT INTO PowerGenerator (Email, PowerGeneratorId, PowerGenerationType, AverageKWH, StorageKWh) values ('fntafhzqe.uhexacvsog@hotmail.com',1, 'wind', 863,908);
INSERT INTO PowerGenerator (Email, PowerGeneratorId, PowerGenerationType, AverageKWH, StorageKWh) values ('lofdibmw.yhhrztbqcd@hotmail.com',1, 'solar-electric', 966,603);
INSERT INTO PowerGenerator (Email, PowerGeneratorId, PowerGenerationType, AverageKWH, StorageKWh) values ('kyqzwjq.qgtxlhlz@outlook.com',1, 'wind', 898,982);
INSERT INTO PowerGenerator (Email, PowerGeneratorId, PowerGenerationType, AverageKWH, StorageKWh) values ('wattdc.kpwmzbip@yahoo.com',1, 'solar-electric', 808,575);
INSERT INTO PowerGenerator (Email, PowerGeneratorId, PowerGenerationType, AverageKWH, StorageKWh) values ('qasge.vkwhx@yahoo.com',1, 'wind', 964,788);
INSERT INTO PowerGenerator (Email, PowerGeneratorId, PowerGenerationType, AverageKWH, StorageKWh) values ('zilqrs.onvmnl@gmail.com',1, 'wind', 792,637);
INSERT INTO PowerGenerator (Email, PowerGeneratorId, PowerGenerationType, AverageKWH, StorageKWh) values ('diztbfzr.vqbzb@gmail.com',1, 'wind', 662,879);
INSERT INTO PowerGenerator (Email, PowerGeneratorId, PowerGenerationType, AverageKWH, StorageKWh) values ('dozaxk.snrqcadfr@hotmail.com',1, 'wind', 523,618);
INSERT INTO PowerGenerator (Email, PowerGeneratorId, PowerGenerationType, AverageKWH, StorageKWh) values ('bwcrbvt.pmsfqbwo@hotmail.com',1, 'wind', 513,631);

--     6. Appliance
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'HeatPump', 'xhzkzad.sckkst@outlook.com', 'MUZ-FH/MSZ-FH High Efficiency Heat Pump System','43295','Mitsubishi Electric');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'Heater', 'ahqejl.csewbslre@outlook.com', 'HHF360V 360-Degree Surround Fan Forced Heater','30659','Honeywell');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'HeatPump', 'fryjjhrez.gnltrdvumm@yahoo.com', 'Infinity 20 Heat Pump with Greenspeed Intelligence','20825','Carrier');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'HeatPump', 'ndpipmp.bjkjk@gmail.com', 'Halcyon HFI Hybrid Flex Inverter Heat Pump System','14522','Fujitsu');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'AirConditioner', 'rhwgp.bhvpfe@outlook.com', 'Infinity 21 Central Air Conditioner','8000','Carrier');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'AirConditioner', 'vlcojiy.fwdjtczp@yahoo.com', 'GSXC18 Air Conditioner','24917','Goodman');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'AirConditioner', 'vsgbgdl.tgftnz@gmail.com', 'GSXC18 Air Conditioner','40303','Goodman');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'HeatPump', 'dhhilddh.yudnpois@yahoo.com', 'Art Cool Mirror Wall-Mounted 12K BTU Heat Pump','19789','LG');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'Heater', 'wvakphra.qdrgftpkk@outlook.com', 'Revillusion 20-Inch Electric Fireplace Log Set','34600','Dimplex');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'Heater', 'asjpka.rcklxq@outlook.com', 'Mica Thermic Panel Heater','54774','DeLonghi');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'HeatPump', 'pytpnqms.dtsnein@outlook.com', 'Infinity 20 Heat Pump with Greenspeed Intelligence','27608','Carrier');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'AirConditioner', 'wnegrv.calkded@yahoo.com', 'RA20 Air Conditioner','18895','Rheem');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'Heater', 'cpixuxabd.qpdbx@gmail.com', 'Portable Space Heater','56998','Dr. Infrared');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'Heater', 'eokjewvo.rolhepl@hotmail.com', '755320 Ceramic Tower Heater','42435','Lasko');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'WaterHeater', 'mktxyyfbjl.kbqhrkxej@gmail.com', 'Super High Efficiency Plus 11 GPM Residential Natural Gas Tankless Water Heater','55389','Rinnai');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'WaterHeater', 'zxdphvm.bnflhn@hotmail.com', 'Defender Safety System 50 Gal. Gas Water Heater','40110','Bradford White');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'HeatPump', 'tmfcqvwei.eccrlwui@yahoo.com', 'Art Cool Mirror Wall-Mounted 12K BTU Heat Pump','15433','LG');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'Heater', 'ovgjn.pngew@outlook.com', 'HHF360V 360-Degree Surround Fan Forced Heater','34893','Honeywell');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'AirConditioner', 'grmngou.wrgrbsbmey@hotmail.com', 'GSXC18 Air Conditioner','16655','Goodman');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'AirConditioner', 'itdzt.kjrhulh@outlook.com', 'RA20 Air Conditioner','44362','Rheem');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'AirConditioner', 'unzqoq.fjhopwiee@outlook.com', 'RA20 Air Conditioner','30234','Rheem');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'WaterHeater', 'khvxmd.lanqe@gmail.com', 'Defender Safety System 50 Gal. Gas Water Heater','47173','Bradford White');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'WaterHeater', 'urstm.lyrgcnn@gmail.com', 'Signature Premier 50 Gallon Short Electric Water Heater','25640','AO Smith');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'AirConditioner', 'hjypic.agcbb@outlook.com', 'GSXC18 Air Conditioner','6464','Goodman');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'HeatPump', 'fqeshxgx.llblpd@gmail.com', 'Art Cool Mirror Wall-Mounted 12K BTU Heat Pump','16273','LG');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'WaterHeater', 'spsmxyozhq.qywtidufjz@gmail.com', 'Performance Platinum 50 Gal. Electric Water Heater','33092','Rheem');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'HeatPump', 'mdreacz.ejbkihgmkw@outlook.com', 'MUZ-FH/MSZ-FH High Efficiency Heat Pump System','5254','Mitsubishi Electric');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'AirConditioner', 'zzzdt.zaxsxftzxv@gmail.com', 'XC25 Air Conditioner','17023','Lennox');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'HeatPump', 'erlmfpw.gvmypognpu@hotmail.com', 'Emura High-Efficiency Heat Pump System','26226','Daikin');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'WaterHeater', 'ccxezue.wuxtawu@gmail.com', '40-Gallon Short 6-Year Gas Water Heater','59256','Whirlpool');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'Heater', 'kcovojowh.wjybftve@gmail.com', 'Mica Thermic Panel Heater','33491','DeLonghi');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'HeatPump', 'pyetbtyxu.bnsgiajmkz@hotmail.com', 'MUZ-FH/MSZ-FH High Efficiency Heat Pump System','27437','Mitsubishi Electric');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'WaterHeater', 'giodplp.hvmwyh@outlook.com', 'Performance Platinum 50 Gal. Electric Water Heater','58242','Rheem');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'WaterHeater', 'xcwfvut.kamua@gmail.com', 'Defender Safety System 50 Gal. Gas Water Heater','57993','Bradford White');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'AirConditioner', 'iolqf.bfwtgsze@yahoo.com', 'GSXC18 Air Conditioner','9780','Goodman');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'HeatPump', 'aqtluaij.tpcqmk@outlook.com', 'MUZ-FH/MSZ-FH High Efficiency Heat Pump System','56988','Mitsubishi Electric');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'AirConditioner', 'uwvdpz.tvmjsi@outlook.com', 'XV20i Variable Speed Air Conditioner','53511','Trane');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'WaterHeater', 'yybzp.ohldcewgzs@outlook.com', 'Defender Safety System 50 Gal. Gas Water Heater','46571','Bradford White');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'Heater', 'epjnhjif.pfbncwh@hotmail.com', 'Revillusion 20-Inch Electric Fireplace Log Set','17924','Dimplex');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'Heater', 'nsarfibcoq.sttulj@outlook.com', '755320 Ceramic Tower Heater','18354','Lasko');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'Heater', 'djttpsh.nnizif@gmail.com', 'HHF360V 360-Degree Surround Fan Forced Heater','33262','Honeywell');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'AirConditioner', 'bgfruxt.bzxaqn@yahoo.com', 'Infinity 21 Central Air Conditioner','41223','Carrier');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'Heater', 'pnlreotd.gycaxkvmvo@hotmail.com', 'Revillusion 20-Inch Electric Fireplace Log Set','38209','Dimplex');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'AirConditioner', 'srzwkfjyo.hgotns@gmail.com', 'Infinity 21 Central Air Conditioner','43014','Carrier');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'AirConditioner', 'ufnerjhy.lplqrstry@yahoo.com', 'XC25 Air Conditioner','49816','Lennox');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'Heater', 'klcnkuqwk.ufazrl@outlook.com', 'HHF360V 360-Degree Surround Fan Forced Heater','55714','Honeywell');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'AirConditioner', 'jorce.jcrvnderk@yahoo.com', 'GSXC18 Air Conditioner','56156','Goodman');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'Heater', 'pjnpi.tohfvsn@outlook.com', 'Portable Space Heater','17648','Dr. Infrared');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'WaterHeater', 'iyyol.glujl@gmail.com', 'Super High Efficiency Plus 11 GPM Residential Natural Gas Tankless Water Heater','33986','Rinnai');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'Heater', 'bmfxvqf.dyewekj@outlook.com', 'Mica Thermic Panel Heater','11871','DeLonghi');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'HeatPump', 'smpwu.gibhncer@hotmail.com', 'Infinity 20 Heat Pump with Greenspeed Intelligence','55845','Carrier');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'WaterHeater', 'dygzz.gqehriguo@hotmail.com', 'Super High Efficiency Plus 11 GPM Residential Natural Gas Tankless Water Heater','23528','Rinnai');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'HeatPump', 'xzwstkiibr.clxbqwvvm@yahoo.com', 'Halcyon HFI Hybrid Flex Inverter Heat Pump System','7872','Fujitsu');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'Heater', 'pywvpw.tbgml@outlook.com', 'Mica Thermic Panel Heater','7487','DeLonghi');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'AirConditioner', 'ptcmpco.jnqalia@outlook.com', 'GSXC18 Air Conditioner','15766','Goodman');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'Heater', 'zwqthuc.xhrjzxwr@hotmail.com', 'Revillusion 20-Inch Electric Fireplace Log Set','55151','Dimplex');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'AirConditioner', 'uralvthzi.jyjhohvvdg@gmail.com', 'XC25 Air Conditioner','59147','Lennox');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'HeatPump', 'sjosrgks.qbdwuqmjl@outlook.com', 'Infinity 20 Heat Pump with Greenspeed Intelligence','23675','Carrier');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'HeatPump', 'ndmqxhli.wlaypuawv@gmail.com', 'Infinity 20 Heat Pump with Greenspeed Intelligence','54483','Carrier');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'Heater', 'itewtwyzw.qdvpfx@outlook.com', 'Portable Space Heater','39335','Dr. Infrared');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'Heater', 'mmwraelwm.uvjrsp@outlook.com', '755320 Ceramic Tower Heater','10174','Lasko');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'HeatPump', 'zttqvvo.nxcxor@outlook.com', 'Art Cool Mirror Wall-Mounted 12K BTU Heat Pump','48011','LG');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'HeatPump', 'hvbac.jzcla@hotmail.com', 'Halcyon HFI Hybrid Flex Inverter Heat Pump System','15588','Fujitsu');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'HeatPump', 'tcgjbbv.tybrggdl@gmail.com', 'MUZ-FH/MSZ-FH High Efficiency Heat Pump System','39652','Mitsubishi Electric');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'Heater', 'gulsthcn.nhabzdc@yahoo.com', 'Revillusion 20-Inch Electric Fireplace Log Set','36553','Dimplex');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'WaterHeater', 'jkmoj.anlzli@gmail.com', 'Signature Premier 50 Gallon Short Electric Water Heater','13278','AO Smith');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'AirConditioner', 'bkbio.yghhi@hotmail.com', 'Infinity 21 Central Air Conditioner','16644','Carrier');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'AirConditioner', 'mxqfsbzvhq.pmdfz@outlook.com', 'XV20i Variable Speed Air Conditioner','14306','Trane');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'HeatPump', 'nxabsvdx.lseiew@hotmail.com', 'Infinity 20 Heat Pump with Greenspeed Intelligence','57918','Carrier');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'WaterHeater', 'dbbxdtzqn.qioarzw@hotmail.com', 'Signature Premier 50 Gallon Short Electric Water Heater','37124','AO Smith');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'AirConditioner', 'dwszhdtxk.hcpjjbcc@gmail.com', 'XV20i Variable Speed Air Conditioner','56854','Trane');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'Heater', 'eynkd.ounorracj@outlook.com', 'HHF360V 360-Degree Surround Fan Forced Heater','18956','Honeywell');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'HeatPump', 'mgpbl.jfkwks@outlook.com', 'Art Cool Mirror Wall-Mounted 12K BTU Heat Pump','55927','LG');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'HeatPump', 'vnqfmfpja.lodgygnunm@outlook.com', 'Art Cool Mirror Wall-Mounted 12K BTU Heat Pump','28500','LG');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'Heater', 'kpcfrihokc.rdaqylsjlm@gmail.com', 'Revillusion 20-Inch Electric Fireplace Log Set','28992','Dimplex');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'WaterHeater', 'qimlly.xxnejproek@hotmail.com', '40-Gallon Short 6-Year Gas Water Heater','19562','Whirlpool');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'Heater', 'opqsbcms.unwlrcpka@hotmail.com', 'HHF360V 360-Degree Surround Fan Forced Heater','26035','Honeywell');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'Heater', 'agsciy.yorxv@outlook.com', 'Mica Thermic Panel Heater','46409','DeLonghi');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'AirConditioner', 'znnjjutr.gnnmt@yahoo.com', 'RA20 Air Conditioner','52543','Rheem');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'Heater', 'zplewtkzdi.hhanyrxh@hotmail.com', 'Mica Thermic Panel Heater','42532','DeLonghi');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'WaterHeater', 'tclplxspg.ertff@gmail.com', 'Defender Safety System 50 Gal. Gas Water Heater','50407','Bradford White');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'WaterHeater', 'nvxofsr.hcrpv@yahoo.com', '40-Gallon Short 6-Year Gas Water Heater','25486','Whirlpool');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'Heater', 'fgaenbx.tirfmblwmb@outlook.com', 'HHF360V 360-Degree Surround Fan Forced Heater','13268','Honeywell');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'Heater', 'fbjnjj.jnhcfp@outlook.com', 'Revillusion 20-Inch Electric Fireplace Log Set','45985','Dimplex');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'AirConditioner', 'ypghd.ocqvp@yahoo.com', 'GSXC18 Air Conditioner','25221','Goodman');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'HeatPump', 'wrebxlyza.zilvomjtr@yahoo.com', 'MUZ-FH/MSZ-FH High Efficiency Heat Pump System','22265','Mitsubishi Electric');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'HeatPump', 'edbsgqp.lsnofunj@hotmail.com', 'Art Cool Mirror Wall-Mounted 12K BTU Heat Pump','29162','LG');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'AirConditioner', 'fntafhzqe.uhexacvsog@hotmail.com', 'Infinity 21 Central Air Conditioner','46148','Carrier');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'HeatPump', 'gsbyss.jlcghlrgtv@gmail.com', 'MUZ-FH/MSZ-FH High Efficiency Heat Pump System','18035','Mitsubishi Electric');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'AirConditioner', 'lofdibmw.yhhrztbqcd@hotmail.com', 'XC25 Air Conditioner','58685','Lennox');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'WaterHeater', 'sbipn.kuqoihyvun@yahoo.com', 'Super High Efficiency Plus 11 GPM Residential Natural Gas Tankless Water Heater','45859','Rinnai');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'HeatPump', 'kyqzwjq.qgtxlhlz@outlook.com', 'Halcyon HFI Hybrid Flex Inverter Heat Pump System','10262','Fujitsu');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'WaterHeater', 'wattdc.kpwmzbip@yahoo.com', 'Defender Safety System 50 Gal. Gas Water Heater','52852','Bradford White');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'Heater', 'qasge.vkwhx@yahoo.com', 'Revillusion 20-Inch Electric Fireplace Log Set','12557','Dimplex');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'WaterHeater', 'zilqrs.onvmnl@gmail.com', 'Super High Efficiency Plus 11 GPM Residential Natural Gas Tankless Water Heater','42197','Rinnai');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'AirConditioner', 'diztbfzr.vqbzb@gmail.com', 'GSXC18 Air Conditioner','25501','Goodman');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'Heater', 'dmemwafc.mxoacset@yahoo.com', 'Portable Space Heater','53606','Dr. Infrared');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'Heater', 'dozaxk.snrqcadfr@hotmail.com', 'Portable Space Heater','37703','Dr. Infrared');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'HeatPump', 'bwcrbvt.pmsfqbwo@hotmail.com', 'MUZ-FH/MSZ-FH High Efficiency Heat Pump System','19127','Mitsubishi Electric');
INSERT INTO Appliance (ApplianceId, Name, Email, ModelName, BTURating, ManufacturerName) values (1,'WaterHeater', 'squsr.ariepax@outlook.com', 'Defender Safety System 50 Gal. Gas Water Heater','46264','Bradford White');

--     7. WaterHeater
INSERT INTO WaterHeater (ApplianceId, Email, Capacity, Temperature, EnergySource) values (1,'mktxyyfbjl.kbqhrkxej@gmail.com', 60.6, 75,'gas');
INSERT INTO WaterHeater (ApplianceId, Email, Capacity, Temperature, EnergySource) values (1,'zxdphvm.bnflhn@hotmail.com', 48.7, 67,'gas');
INSERT INTO WaterHeater (ApplianceId, Email, Capacity, Temperature, EnergySource) values (1,'khvxmd.lanqe@gmail.com', 27.0, 67,'thermosolar');
INSERT INTO WaterHeater (ApplianceId, Email, Capacity, Temperature, EnergySource) values (1,'urstm.lyrgcnn@gmail.com', 31.4, 80,'gas');
INSERT INTO WaterHeater (ApplianceId, Email, Capacity, Temperature, EnergySource) values (1,'spsmxyozhq.qywtidufjz@gmail.com', 68.1, 67,'heat pump');
INSERT INTO WaterHeater (ApplianceId, Email, Capacity, Temperature, EnergySource) values (1,'ccxezue.wuxtawu@gmail.com', 49.6, 80,'heat pump');
INSERT INTO WaterHeater (ApplianceId, Email, Capacity, Temperature, EnergySource) values (1,'giodplp.hvmwyh@outlook.com', 63.5, 74,'gas');
INSERT INTO WaterHeater (ApplianceId, Email, Capacity, Temperature, EnergySource) values (1,'xcwfvut.kamua@gmail.com', 41.3, 80,'thermosolar');
INSERT INTO WaterHeater (ApplianceId, Email, Capacity, Temperature, EnergySource) values (1,'yybzp.ohldcewgzs@outlook.com', 45.8, 72,'thermosolar');
INSERT INTO WaterHeater (ApplianceId, Email, Capacity, Temperature, EnergySource) values (1,'iyyol.glujl@gmail.com', 64.1, 71,'electric');
INSERT INTO WaterHeater (ApplianceId, Email, Capacity, Temperature, EnergySource) values (1,'dygzz.gqehriguo@hotmail.com', 68.7, 74,'thermosolar');
INSERT INTO WaterHeater (ApplianceId, Email, Capacity, Temperature, EnergySource) values (1,'jkmoj.anlzli@gmail.com', 26.6, 71,'electric');
INSERT INTO WaterHeater (ApplianceId, Email, Capacity, Temperature, EnergySource) values (1,'dbbxdtzqn.qioarzw@hotmail.com', 78.0, 68,'thermosolar');
INSERT INTO WaterHeater (ApplianceId, Email, Capacity, Temperature, EnergySource) values (1,'qimlly.xxnejproek@hotmail.com', 57.9, 74,'thermosolar');
INSERT INTO WaterHeater (ApplianceId, Email, Capacity, Temperature, EnergySource) values (1,'tclplxspg.ertff@gmail.com', 26.9, 74,'gas');
INSERT INTO WaterHeater (ApplianceId, Email, Capacity, Temperature, EnergySource) values (1,'nvxofsr.hcrpv@yahoo.com', 32.9, 76,'thermosolar');
INSERT INTO WaterHeater (ApplianceId, Email, Capacity, Temperature, EnergySource) values (1,'sbipn.kuqoihyvun@yahoo.com', 65.9, 65,'gas');
INSERT INTO WaterHeater (ApplianceId, Email, Capacity, Temperature, EnergySource) values (1,'wattdc.kpwmzbip@yahoo.com', 52.4, 77,'gas');
INSERT INTO WaterHeater (ApplianceId, Email, Capacity, Temperature, EnergySource) values (1,'zilqrs.onvmnl@gmail.com', 72.4, 70,'heat pump');
INSERT INTO WaterHeater (ApplianceId, Email, Capacity, Temperature, EnergySource) values (1,'squsr.ariepax@outlook.com', 55.1, 75,'gas');


--     8. AirHandler
INSERT INTO AirHandler (ApplianceId, Email, HeatingCoolingMethod) values (1,'xhzkzad.sckkst@outlook.com','HeatPump');
INSERT INTO AirHandler (ApplianceId, Email, HeatingCoolingMethod) values (1,'ahqejl.csewbslre@outlook.com','Heater');
INSERT INTO AirHandler (ApplianceId, Email, HeatingCoolingMethod) values (1,'fryjjhrez.gnltrdvumm@yahoo.com','HeatPump');
INSERT INTO AirHandler (ApplianceId, Email, HeatingCoolingMethod) values (1,'ndpipmp.bjkjk@gmail.com','HeatPump');
INSERT INTO AirHandler (ApplianceId, Email, HeatingCoolingMethod) values (1,'rhwgp.bhvpfe@outlook.com','AirConditioner');
INSERT INTO AirHandler (ApplianceId, Email, HeatingCoolingMethod) values (1,'vlcojiy.fwdjtczp@yahoo.com','AirConditioner');
INSERT INTO AirHandler (ApplianceId, Email, HeatingCoolingMethod) values (1,'vsgbgdl.tgftnz@gmail.com','AirConditioner');
INSERT INTO AirHandler (ApplianceId, Email, HeatingCoolingMethod) values (1,'dhhilddh.yudnpois@yahoo.com','HeatPump');
INSERT INTO AirHandler (ApplianceId, Email, HeatingCoolingMethod) values (1,'wvakphra.qdrgftpkk@outlook.com','Heater');
INSERT INTO AirHandler (ApplianceId, Email, HeatingCoolingMethod) values (1,'asjpka.rcklxq@outlook.com','Heater');
INSERT INTO AirHandler (ApplianceId, Email, HeatingCoolingMethod) values (1,'pytpnqms.dtsnein@outlook.com','HeatPump');
INSERT INTO AirHandler (ApplianceId, Email, HeatingCoolingMethod) values (1,'wnegrv.calkded@yahoo.com','AirConditioner');
INSERT INTO AirHandler (ApplianceId, Email, HeatingCoolingMethod) values (1,'cpixuxabd.qpdbx@gmail.com','Heater');
INSERT INTO AirHandler (ApplianceId, Email, HeatingCoolingMethod) values (1,'eokjewvo.rolhepl@hotmail.com','Heater');
INSERT INTO AirHandler (ApplianceId, Email, HeatingCoolingMethod) values (1,'tmfcqvwei.eccrlwui@yahoo.com','HeatPump');
INSERT INTO AirHandler (ApplianceId, Email, HeatingCoolingMethod) values (1,'ovgjn.pngew@outlook.com','Heater');
INSERT INTO AirHandler (ApplianceId, Email, HeatingCoolingMethod) values (1,'grmngou.wrgrbsbmey@hotmail.com','AirConditioner');
INSERT INTO AirHandler (ApplianceId, Email, HeatingCoolingMethod) values (1,'itdzt.kjrhulh@outlook.com','AirConditioner');
INSERT INTO AirHandler (ApplianceId, Email, HeatingCoolingMethod) values (1,'unzqoq.fjhopwiee@outlook.com','AirConditioner');
INSERT INTO AirHandler (ApplianceId, Email, HeatingCoolingMethod) values (1,'hjypic.agcbb@outlook.com','AirConditioner');
INSERT INTO AirHandler (ApplianceId, Email, HeatingCoolingMethod) values (1,'fqeshxgx.llblpd@gmail.com','HeatPump');
INSERT INTO AirHandler (ApplianceId, Email, HeatingCoolingMethod) values (1,'mdreacz.ejbkihgmkw@outlook.com','HeatPump');
INSERT INTO AirHandler (ApplianceId, Email, HeatingCoolingMethod) values (1,'zzzdt.zaxsxftzxv@gmail.com','AirConditioner');
INSERT INTO AirHandler (ApplianceId, Email, HeatingCoolingMethod) values (1,'erlmfpw.gvmypognpu@hotmail.com','HeatPump');
INSERT INTO AirHandler (ApplianceId, Email, HeatingCoolingMethod) values (1,'kcovojowh.wjybftve@gmail.com','Heater');
INSERT INTO AirHandler (ApplianceId, Email, HeatingCoolingMethod) values (1,'pyetbtyxu.bnsgiajmkz@hotmail.com','HeatPump');
INSERT INTO AirHandler (ApplianceId, Email, HeatingCoolingMethod) values (1,'iolqf.bfwtgsze@yahoo.com','AirConditioner');
INSERT INTO AirHandler (ApplianceId, Email, HeatingCoolingMethod) values (1,'aqtluaij.tpcqmk@outlook.com','HeatPump');
INSERT INTO AirHandler (ApplianceId, Email, HeatingCoolingMethod) values (1,'uwvdpz.tvmjsi@outlook.com','AirConditioner');
INSERT INTO AirHandler (ApplianceId, Email, HeatingCoolingMethod) values (1,'epjnhjif.pfbncwh@hotmail.com','Heater');
INSERT INTO AirHandler (ApplianceId, Email, HeatingCoolingMethod) values (1,'nsarfibcoq.sttulj@outlook.com','Heater');
INSERT INTO AirHandler (ApplianceId, Email, HeatingCoolingMethod) values (1,'djttpsh.nnizif@gmail.com','Heater');
INSERT INTO AirHandler (ApplianceId, Email, HeatingCoolingMethod) values (1,'bgfruxt.bzxaqn@yahoo.com','AirConditioner');
INSERT INTO AirHandler (ApplianceId, Email, HeatingCoolingMethod) values (1,'pnlreotd.gycaxkvmvo@hotmail.com','Heater');
INSERT INTO AirHandler (ApplianceId, Email, HeatingCoolingMethod) values (1,'srzwkfjyo.hgotns@gmail.com','AirConditioner');
INSERT INTO AirHandler (ApplianceId, Email, HeatingCoolingMethod) values (1,'ufnerjhy.lplqrstry@yahoo.com','AirConditioner');
INSERT INTO AirHandler (ApplianceId, Email, HeatingCoolingMethod) values (1,'klcnkuqwk.ufazrl@outlook.com','Heater');
INSERT INTO AirHandler (ApplianceId, Email, HeatingCoolingMethod) values (1,'jorce.jcrvnderk@yahoo.com','AirConditioner');
INSERT INTO AirHandler (ApplianceId, Email, HeatingCoolingMethod) values (1,'pjnpi.tohfvsn@outlook.com','Heater');
INSERT INTO AirHandler (ApplianceId, Email, HeatingCoolingMethod) values (1,'bmfxvqf.dyewekj@outlook.com','Heater');
INSERT INTO AirHandler (ApplianceId, Email, HeatingCoolingMethod) values (1,'smpwu.gibhncer@hotmail.com','HeatPump');
INSERT INTO AirHandler (ApplianceId, Email, HeatingCoolingMethod) values (1,'xzwstkiibr.clxbqwvvm@yahoo.com','HeatPump');
INSERT INTO AirHandler (ApplianceId, Email, HeatingCoolingMethod) values (1,'pywvpw.tbgml@outlook.com','Heater');
INSERT INTO AirHandler (ApplianceId, Email, HeatingCoolingMethod) values (1,'ptcmpco.jnqalia@outlook.com','AirConditioner');
INSERT INTO AirHandler (ApplianceId, Email, HeatingCoolingMethod) values (1,'zwqthuc.xhrjzxwr@hotmail.com','Heater');
INSERT INTO AirHandler (ApplianceId, Email, HeatingCoolingMethod) values (1,'uralvthzi.jyjhohvvdg@gmail.com','AirConditioner');
INSERT INTO AirHandler (ApplianceId, Email, HeatingCoolingMethod) values (1,'sjosrgks.qbdwuqmjl@outlook.com','HeatPump');
INSERT INTO AirHandler (ApplianceId, Email, HeatingCoolingMethod) values (1,'ndmqxhli.wlaypuawv@gmail.com','HeatPump');
INSERT INTO AirHandler (ApplianceId, Email, HeatingCoolingMethod) values (1,'itewtwyzw.qdvpfx@outlook.com','Heater');
INSERT INTO AirHandler (ApplianceId, Email, HeatingCoolingMethod) values (1,'mmwraelwm.uvjrsp@outlook.com','Heater');
INSERT INTO AirHandler (ApplianceId, Email, HeatingCoolingMethod) values (1,'zttqvvo.nxcxor@outlook.com','HeatPump');
INSERT INTO AirHandler (ApplianceId, Email, HeatingCoolingMethod) values (1,'hvbac.jzcla@hotmail.com','HeatPump');
INSERT INTO AirHandler (ApplianceId, Email, HeatingCoolingMethod) values (1,'tcgjbbv.tybrggdl@gmail.com','HeatPump');
INSERT INTO AirHandler (ApplianceId, Email, HeatingCoolingMethod) values (1,'gulsthcn.nhabzdc@yahoo.com','Heater');
INSERT INTO AirHandler (ApplianceId, Email, HeatingCoolingMethod) values (1,'bkbio.yghhi@hotmail.com','AirConditioner');
INSERT INTO AirHandler (ApplianceId, Email, HeatingCoolingMethod) values (1,'mxqfsbzvhq.pmdfz@outlook.com','AirConditioner');
INSERT INTO AirHandler (ApplianceId, Email, HeatingCoolingMethod) values (1,'nxabsvdx.lseiew@hotmail.com','HeatPump');
INSERT INTO AirHandler (ApplianceId, Email, HeatingCoolingMethod) values (1,'dwszhdtxk.hcpjjbcc@gmail.com','AirConditioner');
INSERT INTO AirHandler (ApplianceId, Email, HeatingCoolingMethod) values (1,'eynkd.ounorracj@outlook.com','Heater');
INSERT INTO AirHandler (ApplianceId, Email, HeatingCoolingMethod) values (1,'mgpbl.jfkwks@outlook.com','HeatPump');
INSERT INTO AirHandler (ApplianceId, Email, HeatingCoolingMethod) values (1,'vnqfmfpja.lodgygnunm@outlook.com','HeatPump');
INSERT INTO AirHandler (ApplianceId, Email, HeatingCoolingMethod) values (1,'kpcfrihokc.rdaqylsjlm@gmail.com','Heater');
INSERT INTO AirHandler (ApplianceId, Email, HeatingCoolingMethod) values (1,'opqsbcms.unwlrcpka@hotmail.com','Heater');
INSERT INTO AirHandler (ApplianceId, Email, HeatingCoolingMethod) values (1,'agsciy.yorxv@outlook.com','Heater');
INSERT INTO AirHandler (ApplianceId, Email, HeatingCoolingMethod) values (1,'znnjjutr.gnnmt@yahoo.com','AirConditioner');
INSERT INTO AirHandler (ApplianceId, Email, HeatingCoolingMethod) values (1,'zplewtkzdi.hhanyrxh@hotmail.com','Heater');
INSERT INTO AirHandler (ApplianceId, Email, HeatingCoolingMethod) values (1,'fgaenbx.tirfmblwmb@outlook.com','Heater');
INSERT INTO AirHandler (ApplianceId, Email, HeatingCoolingMethod) values (1,'fbjnjj.jnhcfp@outlook.com','Heater');
INSERT INTO AirHandler (ApplianceId, Email, HeatingCoolingMethod) values (1,'ypghd.ocqvp@yahoo.com','AirConditioner');
INSERT INTO AirHandler (ApplianceId, Email, HeatingCoolingMethod) values (1,'wrebxlyza.zilvomjtr@yahoo.com','HeatPump');
INSERT INTO AirHandler (ApplianceId, Email, HeatingCoolingMethod) values (1,'edbsgqp.lsnofunj@hotmail.com','HeatPump');
INSERT INTO AirHandler (ApplianceId, Email, HeatingCoolingMethod) values (1,'fntafhzqe.uhexacvsog@hotmail.com','AirConditioner');
INSERT INTO AirHandler (ApplianceId, Email, HeatingCoolingMethod) values (1,'gsbyss.jlcghlrgtv@gmail.com','HeatPump');
INSERT INTO AirHandler (ApplianceId, Email, HeatingCoolingMethod) values (1,'lofdibmw.yhhrztbqcd@hotmail.com','AirConditioner');
INSERT INTO AirHandler (ApplianceId, Email, HeatingCoolingMethod) values (1,'kyqzwjq.qgtxlhlz@outlook.com','HeatPump');
INSERT INTO AirHandler (ApplianceId, Email, HeatingCoolingMethod) values (1,'qasge.vkwhx@yahoo.com','Heater');
INSERT INTO AirHandler (ApplianceId, Email, HeatingCoolingMethod) values (1,'diztbfzr.vqbzb@gmail.com','AirConditioner');
INSERT INTO AirHandler (ApplianceId, Email, HeatingCoolingMethod) values (1,'dmemwafc.mxoacset@yahoo.com','Heater');
INSERT INTO AirHandler (ApplianceId, Email, HeatingCoolingMethod) values (1,'dozaxk.snrqcadfr@hotmail.com','Heater');
INSERT INTO AirHandler (ApplianceId, Email, HeatingCoolingMethod) values (1,'bwcrbvt.pmsfqbwo@hotmail.com','HeatPump');

--     9. AirConditioner
INSERT INTO AirConditioner (ApplianceId, Email, EnergyEfficiencyRatio) values (1,'rhwgp.bhvpfe@outlook.com',30.7);
INSERT INTO AirConditioner (ApplianceId, Email, EnergyEfficiencyRatio) values (1,'vlcojiy.fwdjtczp@yahoo.com',23.4);
INSERT INTO AirConditioner (ApplianceId, Email, EnergyEfficiencyRatio) values (1,'vsgbgdl.tgftnz@gmail.com',28.6);
INSERT INTO AirConditioner (ApplianceId, Email, EnergyEfficiencyRatio) values (1,'wnegrv.calkded@yahoo.com',24.4);
INSERT INTO AirConditioner (ApplianceId, Email, EnergyEfficiencyRatio) values (1,'grmngou.wrgrbsbmey@hotmail.com',26.8);
INSERT INTO AirConditioner (ApplianceId, Email, EnergyEfficiencyRatio) values (1,'itdzt.kjrhulh@outlook.com',12.1);
INSERT INTO AirConditioner (ApplianceId, Email, EnergyEfficiencyRatio) values (1,'unzqoq.fjhopwiee@outlook.com',29.2);
INSERT INTO AirConditioner (ApplianceId, Email, EnergyEfficiencyRatio) values (1,'hjypic.agcbb@outlook.com',28.9);
INSERT INTO AirConditioner (ApplianceId, Email, EnergyEfficiencyRatio) values (1,'zzzdt.zaxsxftzxv@gmail.com',10.3);
INSERT INTO AirConditioner (ApplianceId, Email, EnergyEfficiencyRatio) values (1,'iolqf.bfwtgsze@yahoo.com',18.8);
INSERT INTO AirConditioner (ApplianceId, Email, EnergyEfficiencyRatio) values (1,'uwvdpz.tvmjsi@outlook.com',15.0);
INSERT INTO AirConditioner (ApplianceId, Email, EnergyEfficiencyRatio) values (1,'bgfruxt.bzxaqn@yahoo.com',20.0);
INSERT INTO AirConditioner (ApplianceId, Email, EnergyEfficiencyRatio) values (1,'srzwkfjyo.hgotns@gmail.com',21.3);
INSERT INTO AirConditioner (ApplianceId, Email, EnergyEfficiencyRatio) values (1,'ufnerjhy.lplqrstry@yahoo.com',17.6);
INSERT INTO AirConditioner (ApplianceId, Email, EnergyEfficiencyRatio) values (1,'jorce.jcrvnderk@yahoo.com',17.4);
INSERT INTO AirConditioner (ApplianceId, Email, EnergyEfficiencyRatio) values (1,'ptcmpco.jnqalia@outlook.com',22.4);
INSERT INTO AirConditioner (ApplianceId, Email, EnergyEfficiencyRatio) values (1,'uralvthzi.jyjhohvvdg@gmail.com',24.4);
INSERT INTO AirConditioner (ApplianceId, Email, EnergyEfficiencyRatio) values (1,'bkbio.yghhi@hotmail.com',27.3);
INSERT INTO AirConditioner (ApplianceId, Email, EnergyEfficiencyRatio) values (1,'mxqfsbzvhq.pmdfz@outlook.com',15.6);
INSERT INTO AirConditioner (ApplianceId, Email, EnergyEfficiencyRatio) values (1,'dwszhdtxk.hcpjjbcc@gmail.com',27.3);
INSERT INTO AirConditioner (ApplianceId, Email, EnergyEfficiencyRatio) values (1,'znnjjutr.gnnmt@yahoo.com',26.4);
INSERT INTO AirConditioner (ApplianceId, Email, EnergyEfficiencyRatio) values (1,'ypghd.ocqvp@yahoo.com',10.1);
INSERT INTO AirConditioner (ApplianceId, Email, EnergyEfficiencyRatio) values (1,'fntafhzqe.uhexacvsog@hotmail.com',29.8);
INSERT INTO AirConditioner (ApplianceId, Email, EnergyEfficiencyRatio) values (1,'lofdibmw.yhhrztbqcd@hotmail.com',12.3);
INSERT INTO AirConditioner (ApplianceId, Email, EnergyEfficiencyRatio) values (1,'diztbfzr.vqbzb@gmail.com',16.6);

--     10. Heater
INSERT INTO Heater (ApplianceId, Email, HeaterEnergySource) values (1,'ahqejl.csewbslre@outlook.com','gas');
INSERT INTO Heater (ApplianceId, Email, HeaterEnergySource) values (1,'wvakphra.qdrgftpkk@outlook.com','electric');
INSERT INTO Heater (ApplianceId, Email, HeaterEnergySource) values (1,'asjpka.rcklxq@outlook.com','electric');
INSERT INTO Heater (ApplianceId, Email, HeaterEnergySource) values (1,'cpixuxabd.qpdbx@gmail.com','fuel oil');
INSERT INTO Heater (ApplianceId, Email, HeaterEnergySource) values (1,'eokjewvo.rolhepl@hotmail.com','electric');
INSERT INTO Heater (ApplianceId, Email, HeaterEnergySource) values (1,'ovgjn.pngew@outlook.com','electric');
INSERT INTO Heater (ApplianceId, Email, HeaterEnergySource) values (1,'kcovojowh.wjybftve@gmail.com','fuel oil');
INSERT INTO Heater (ApplianceId, Email, HeaterEnergySource) values (1,'epjnhjif.pfbncwh@hotmail.com','gas');
INSERT INTO Heater (ApplianceId, Email, HeaterEnergySource) values (1,'nsarfibcoq.sttulj@outlook.com','gas');
INSERT INTO Heater (ApplianceId, Email, HeaterEnergySource) values (1,'djttpsh.nnizif@gmail.com','fuel oil');
INSERT INTO Heater (ApplianceId, Email, HeaterEnergySource) values (1,'pnlreotd.gycaxkvmvo@hotmail.com','gas');
INSERT INTO Heater (ApplianceId, Email, HeaterEnergySource) values (1,'klcnkuqwk.ufazrl@outlook.com','electric');
INSERT INTO Heater (ApplianceId, Email, HeaterEnergySource) values (1,'pjnpi.tohfvsn@outlook.com','gas');
INSERT INTO Heater (ApplianceId, Email, HeaterEnergySource) values (1,'bmfxvqf.dyewekj@outlook.com','fuel oil');
INSERT INTO Heater (ApplianceId, Email, HeaterEnergySource) values (1,'pywvpw.tbgml@outlook.com','electric');
INSERT INTO Heater (ApplianceId, Email, HeaterEnergySource) values (1,'zwqthuc.xhrjzxwr@hotmail.com','electric');
INSERT INTO Heater (ApplianceId, Email, HeaterEnergySource) values (1,'itewtwyzw.qdvpfx@outlook.com','gas');
INSERT INTO Heater (ApplianceId, Email, HeaterEnergySource) values (1,'mmwraelwm.uvjrsp@outlook.com','fuel oil');
INSERT INTO Heater (ApplianceId, Email, HeaterEnergySource) values (1,'gulsthcn.nhabzdc@yahoo.com','electric');
INSERT INTO Heater (ApplianceId, Email, HeaterEnergySource) values (1,'eynkd.ounorracj@outlook.com','fuel oil');
INSERT INTO Heater (ApplianceId, Email, HeaterEnergySource) values (1,'kpcfrihokc.rdaqylsjlm@gmail.com','electric');
INSERT INTO Heater (ApplianceId, Email, HeaterEnergySource) values (1,'opqsbcms.unwlrcpka@hotmail.com','electric');
INSERT INTO Heater (ApplianceId, Email, HeaterEnergySource) values (1,'agsciy.yorxv@outlook.com','electric');
INSERT INTO Heater (ApplianceId, Email, HeaterEnergySource) values (1,'zplewtkzdi.hhanyrxh@hotmail.com','fuel oil');
INSERT INTO Heater (ApplianceId, Email, HeaterEnergySource) values (1,'fgaenbx.tirfmblwmb@outlook.com','fuel oil');
INSERT INTO Heater (ApplianceId, Email, HeaterEnergySource) values (1,'fbjnjj.jnhcfp@outlook.com','electric');
INSERT INTO Heater (ApplianceId, Email, HeaterEnergySource) values (1,'qasge.vkwhx@yahoo.com','electric');
INSERT INTO Heater (ApplianceId, Email, HeaterEnergySource) values (1,'dmemwafc.mxoacset@yahoo.com','electric');
INSERT INTO Heater (ApplianceId, Email, HeaterEnergySource) values (1,'dozaxk.snrqcadfr@hotmail.com','fuel oil');

--     11. HeatPump
INSERT INTO HeatPump (ApplianceId, Email, SeasonalEnergyEfficiencyRating, HeatingSeasonalPerformanceFactor) values (1,'xhzkzad.sckkst@outlook.com',14.0,14.7);
INSERT INTO HeatPump (ApplianceId, Email, SeasonalEnergyEfficiencyRating, HeatingSeasonalPerformanceFactor) values (1,'fryjjhrez.gnltrdvumm@yahoo.com',15.6,9.4);
INSERT INTO HeatPump (ApplianceId, Email, SeasonalEnergyEfficiencyRating, HeatingSeasonalPerformanceFactor) values (1,'ndpipmp.bjkjk@gmail.com',15.4,5.8);
INSERT INTO HeatPump (ApplianceId, Email, SeasonalEnergyEfficiencyRating, HeatingSeasonalPerformanceFactor) values (1,'dhhilddh.yudnpois@yahoo.com',31.0,10.4);
INSERT INTO HeatPump (ApplianceId, Email, SeasonalEnergyEfficiencyRating, HeatingSeasonalPerformanceFactor) values (1,'pytpnqms.dtsnein@outlook.com',14.2,9.1);
INSERT INTO HeatPump (ApplianceId, Email, SeasonalEnergyEfficiencyRating, HeatingSeasonalPerformanceFactor) values (1,'tmfcqvwei.eccrlwui@yahoo.com',13.2,13.8);
INSERT INTO HeatPump (ApplianceId, Email, SeasonalEnergyEfficiencyRating, HeatingSeasonalPerformanceFactor) values (1,'fqeshxgx.llblpd@gmail.com',28.7,8.5);
INSERT INTO HeatPump (ApplianceId, Email, SeasonalEnergyEfficiencyRating, HeatingSeasonalPerformanceFactor) values (1,'mdreacz.ejbkihgmkw@outlook.com',19.1,14.6);
INSERT INTO HeatPump (ApplianceId, Email, SeasonalEnergyEfficiencyRating, HeatingSeasonalPerformanceFactor) values (1,'erlmfpw.gvmypognpu@hotmail.com',15.3,14.3);
INSERT INTO HeatPump (ApplianceId, Email, SeasonalEnergyEfficiencyRating, HeatingSeasonalPerformanceFactor) values (1,'pyetbtyxu.bnsgiajmkz@hotmail.com',11.6,15.8);
INSERT INTO HeatPump (ApplianceId, Email, SeasonalEnergyEfficiencyRating, HeatingSeasonalPerformanceFactor) values (1,'aqtluaij.tpcqmk@outlook.com',27.6,15.3);
INSERT INTO HeatPump (ApplianceId, Email, SeasonalEnergyEfficiencyRating, HeatingSeasonalPerformanceFactor) values (1,'smpwu.gibhncer@hotmail.com',21.0,8.6);
INSERT INTO HeatPump (ApplianceId, Email, SeasonalEnergyEfficiencyRating, HeatingSeasonalPerformanceFactor) values (1,'xzwstkiibr.clxbqwvvm@yahoo.com',12.6,6.5);
INSERT INTO HeatPump (ApplianceId, Email, SeasonalEnergyEfficiencyRating, HeatingSeasonalPerformanceFactor) values (1,'sjosrgks.qbdwuqmjl@outlook.com',31.0,6.3);
INSERT INTO HeatPump (ApplianceId, Email, SeasonalEnergyEfficiencyRating, HeatingSeasonalPerformanceFactor) values (1,'ndmqxhli.wlaypuawv@gmail.com',27.5,15.4);
INSERT INTO HeatPump (ApplianceId, Email, SeasonalEnergyEfficiencyRating, HeatingSeasonalPerformanceFactor) values (1,'zttqvvo.nxcxor@outlook.com',13.8,7.0);
INSERT INTO HeatPump (ApplianceId, Email, SeasonalEnergyEfficiencyRating, HeatingSeasonalPerformanceFactor) values (1,'hvbac.jzcla@hotmail.com',24.7,11.8);
INSERT INTO HeatPump (ApplianceId, Email, SeasonalEnergyEfficiencyRating, HeatingSeasonalPerformanceFactor) values (1,'tcgjbbv.tybrggdl@gmail.com',19.1,6.6);
INSERT INTO HeatPump (ApplianceId, Email, SeasonalEnergyEfficiencyRating, HeatingSeasonalPerformanceFactor) values (1,'nxabsvdx.lseiew@hotmail.com',13.7,6.1);
INSERT INTO HeatPump (ApplianceId, Email, SeasonalEnergyEfficiencyRating, HeatingSeasonalPerformanceFactor) values (1,'mgpbl.jfkwks@outlook.com',23.2,11.7);
INSERT INTO HeatPump (ApplianceId, Email, SeasonalEnergyEfficiencyRating, HeatingSeasonalPerformanceFactor) values (1,'vnqfmfpja.lodgygnunm@outlook.com',10.8,11.4);
INSERT INTO HeatPump (ApplianceId, Email, SeasonalEnergyEfficiencyRating, HeatingSeasonalPerformanceFactor) values (1,'wrebxlyza.zilvomjtr@yahoo.com',22.3,11.0);
INSERT INTO HeatPump (ApplianceId, Email, SeasonalEnergyEfficiencyRating, HeatingSeasonalPerformanceFactor) values (1,'edbsgqp.lsnofunj@hotmail.com',24.9,12.9);
INSERT INTO HeatPump (ApplianceId, Email, SeasonalEnergyEfficiencyRating, HeatingSeasonalPerformanceFactor) values (1,'gsbyss.jlcghlrgtv@gmail.com',27.1,9.0);
INSERT INTO HeatPump (ApplianceId, Email, SeasonalEnergyEfficiencyRating, HeatingSeasonalPerformanceFactor) values (1,'kyqzwjq.qgtxlhlz@outlook.com',19.0,10.6);
INSERT INTO HeatPump (ApplianceId, Email, SeasonalEnergyEfficiencyRating, HeatingSeasonalPerformanceFactor) values (1,'bwcrbvt.pmsfqbwo@hotmail.com',26.3,9.1);
