INSERT INTO UtilityType (Email, UtilityType) values ('xhzkzad.sckkst@outlook.com','steam');
INSERT INTO UtilityType (Email, UtilityType) values ('ahqejl.csewbslre@outlook.com','steam');
INSERT INTO UtilityType (Email, UtilityType) values ('fryjjhrez.gnltrdvumm@yahoo.com','gas');
INSERT INTO UtilityType (Email, UtilityType) values ('ndpipmp.bjkjk@gmail.com','gas');
INSERT INTO UtilityType (Email, UtilityType) values ('rhwgp.bhvpfe@outlook.com','gas');
INSERT INTO UtilityType (Email, UtilityType) values ('vlcojiy.fwdjtczp@yahoo.com','fuel oil');
INSERT INTO UtilityType (Email, UtilityType) values ('vsgbgdl.tgftnz@gmail.com','electric');
INSERT INTO UtilityType (Email, UtilityType) values ('dhhilddh.yudnpois@yahoo.com','gas');
INSERT INTO UtilityType (Email, UtilityType) values ('wvakphra.qdrgftpkk@outlook.com','off-the-grid');
INSERT INTO UtilityType (Email, UtilityType) values ('asjpka.rcklxq@outlook.com','off-the-grid');
INSERT INTO UtilityType (Email, UtilityType) values ('pytpnqms.dtsnein@outlook.com','electric');
INSERT INTO UtilityType (Email, UtilityType) values ('wnegrv.calkded@yahoo.com','gas');
INSERT INTO UtilityType (Email, UtilityType) values ('cpixuxabd.qpdbx@gmail.com','steam');
INSERT INTO UtilityType (Email, UtilityType) values ('eokjewvo.rolhepl@hotmail.com','electric');
INSERT INTO UtilityType (Email, UtilityType) values ('mktxyyfbjl.kbqhrkxej@gmail.com','electric');
INSERT INTO UtilityType (Email, UtilityType) values ('zxdphvm.bnflhn@hotmail.com','electric');
INSERT INTO UtilityType (Email, UtilityType) values ('tmfcqvwei.eccrlwui@yahoo.com','off-the-grid');
INSERT INTO UtilityType (Email, UtilityType) values ('ovgjn.pngew@outlook.com','electric');
INSERT INTO UtilityType (Email, UtilityType) values ('grmngou.wrgrbsbmey@hotmail.com','off-the-grid');
INSERT INTO UtilityType (Email, UtilityType) values ('itdzt.kjrhulh@outlook.com','gas');
INSERT INTO UtilityType (Email, UtilityType) values ('unzqoq.fjhopwiee@outlook.com','electric');
INSERT INTO UtilityType (Email, UtilityType) values ('khvxmd.lanqe@gmail.com','gas');
INSERT INTO UtilityType (Email, UtilityType) values ('urstm.lyrgcnn@gmail.com','electric');
INSERT INTO UtilityType (Email, UtilityType) values ('hjypic.agcbb@outlook.com','gas');
INSERT INTO UtilityType (Email, UtilityType) values ('fqeshxgx.llblpd@gmail.com','off-the-grid');
INSERT INTO UtilityType (Email, UtilityType) values ('spsmxyozhq.qywtidufjz@gmail.com','gas');
INSERT INTO UtilityType (Email, UtilityType) values ('mdreacz.ejbkihgmkw@outlook.com','electric');
INSERT INTO UtilityType (Email, UtilityType) values ('zzzdt.zaxsxftzxv@gmail.com','off-the-grid');
INSERT INTO UtilityType (Email, UtilityType) values ('erlmfpw.gvmypognpu@hotmail.com','steam');
INSERT INTO UtilityType (Email, UtilityType) values ('ccxezue.wuxtawu@gmail.com','fuel oil');
INSERT INTO UtilityType (Email, UtilityType) values ('kcovojowh.wjybftve@gmail.com','electric');
INSERT INTO UtilityType (Email, UtilityType) values ('pyetbtyxu.bnsgiajmkz@hotmail.com','fuel oil');
INSERT INTO UtilityType (Email, UtilityType) values ('giodplp.hvmwyh@outlook.com','off-the-grid');
INSERT INTO UtilityType (Email, UtilityType) values ('xcwfvut.kamua@gmail.com','steam');
INSERT INTO UtilityType (Email, UtilityType) values ('iolqf.bfwtgsze@yahoo.com','gas');
INSERT INTO UtilityType (Email, UtilityType) values ('aqtluaij.tpcqmk@outlook.com','gas');
INSERT INTO UtilityType (Email, UtilityType) values ('uwvdpz.tvmjsi@outlook.com','off-the-grid');
INSERT INTO UtilityType (Email, UtilityType) values ('yybzp.ohldcewgzs@outlook.com','steam');
INSERT INTO UtilityType (Email, UtilityType) values ('epjnhjif.pfbncwh@hotmail.com','electric');
INSERT INTO UtilityType (Email, UtilityType) values ('nsarfibcoq.sttulj@outlook.com','fuel oil');
INSERT INTO UtilityType (Email, UtilityType) values ('djttpsh.nnizif@gmail.com','off-the-grid');
INSERT INTO UtilityType (Email, UtilityType) values ('bgfruxt.bzxaqn@yahoo.com','electric');
INSERT INTO UtilityType (Email, UtilityType) values ('pnlreotd.gycaxkvmvo@hotmail.com','gas');
INSERT INTO UtilityType (Email, UtilityType) values ('srzwkfjyo.hgotns@gmail.com','fuel oil');
INSERT INTO UtilityType (Email, UtilityType) values ('ufnerjhy.lplqrstry@yahoo.com','steam');
INSERT INTO UtilityType (Email, UtilityType) values ('klcnkuqwk.ufazrl@outlook.com','off-the-grid');
INSERT INTO UtilityType (Email, UtilityType) values ('jorce.jcrvnderk@yahoo.com','gas');
INSERT INTO UtilityType (Email, UtilityType) values ('pjnpi.tohfvsn@outlook.com','fuel oil');
INSERT INTO UtilityType (Email, UtilityType) values ('iyyol.glujl@gmail.com','off-the-grid');
INSERT INTO UtilityType (Email, UtilityType) values ('bmfxvqf.dyewekj@outlook.com','electric');
INSERT INTO UtilityType (Email, UtilityType) values ('smpwu.gibhncer@hotmail.com','steam');
INSERT INTO UtilityType (Email, UtilityType) values ('dygzz.gqehriguo@hotmail.com','fuel oil');
INSERT INTO UtilityType (Email, UtilityType) values ('xzwstkiibr.clxbqwvvm@yahoo.com','steam');
INSERT INTO UtilityType (Email, UtilityType) values ('pywvpw.tbgml@outlook.com','electric');
INSERT INTO UtilityType (Email, UtilityType) values ('ptcmpco.jnqalia@outlook.com','off-the-grid');
INSERT INTO UtilityType (Email, UtilityType) values ('zwqthuc.xhrjzxwr@hotmail.com','electric');
INSERT INTO UtilityType (Email, UtilityType) values ('uralvthzi.jyjhohvvdg@gmail.com','gas');
INSERT INTO UtilityType (Email, UtilityType) values ('sjosrgks.qbdwuqmjl@outlook.com','gas');
INSERT INTO UtilityType (Email, UtilityType) values ('ndmqxhli.wlaypuawv@gmail.com','electric');
INSERT INTO UtilityType (Email, UtilityType) values ('itewtwyzw.qdvpfx@outlook.com','steam');
INSERT INTO UtilityType (Email, UtilityType) values ('mmwraelwm.uvjrsp@outlook.com','electric');
INSERT INTO UtilityType (Email, UtilityType) values ('zttqvvo.nxcxor@outlook.com','electric');
INSERT INTO UtilityType (Email, UtilityType) values ('hvbac.jzcla@hotmail.com','steam');
INSERT INTO UtilityType (Email, UtilityType) values ('tcgjbbv.tybrggdl@gmail.com','fuel oil');
INSERT INTO UtilityType (Email, UtilityType) values ('gulsthcn.nhabzdc@yahoo.com','off-the-grid');
INSERT INTO UtilityType (Email, UtilityType) values ('jkmoj.anlzli@gmail.com','fuel oil');
INSERT INTO UtilityType (Email, UtilityType) values ('bkbio.yghhi@hotmail.com','electric');
INSERT INTO UtilityType (Email, UtilityType) values ('mxqfsbzvhq.pmdfz@outlook.com','steam');
INSERT INTO UtilityType (Email, UtilityType) values ('nxabsvdx.lseiew@hotmail.com','gas');
INSERT INTO UtilityType (Email, UtilityType) values ('dbbxdtzqn.qioarzw@hotmail.com','steam');
INSERT INTO UtilityType (Email, UtilityType) values ('dwszhdtxk.hcpjjbcc@gmail.com','gas');
INSERT INTO UtilityType (Email, UtilityType) values ('eynkd.ounorracj@outlook.com','steam');
INSERT INTO UtilityType (Email, UtilityType) values ('mgpbl.jfkwks@outlook.com','off-the-grid');
INSERT INTO UtilityType (Email, UtilityType) values ('vnqfmfpja.lodgygnunm@outlook.com','steam');
INSERT INTO UtilityType (Email, UtilityType) values ('kpcfrihokc.rdaqylsjlm@gmail.com','steam');
INSERT INTO UtilityType (Email, UtilityType) values ('qimlly.xxnejproek@hotmail.com','gas');
INSERT INTO UtilityType (Email, UtilityType) values ('opqsbcms.unwlrcpka@hotmail.com','electric');
INSERT INTO UtilityType (Email, UtilityType) values ('agsciy.yorxv@outlook.com','gas');
INSERT INTO UtilityType (Email, UtilityType) values ('znnjjutr.gnnmt@yahoo.com','steam');
INSERT INTO UtilityType (Email, UtilityType) values ('zplewtkzdi.hhanyrxh@hotmail.com','electric');
INSERT INTO UtilityType (Email, UtilityType) values ('tclplxspg.ertff@gmail.com','off-the-grid');
INSERT INTO UtilityType (Email, UtilityType) values ('nvxofsr.hcrpv@yahoo.com','off-the-grid');
INSERT INTO UtilityType (Email, UtilityType) values ('fgaenbx.tirfmblwmb@outlook.com','steam');
INSERT INTO UtilityType (Email, UtilityType) values ('fbjnjj.jnhcfp@outlook.com','steam');
INSERT INTO UtilityType (Email, UtilityType) values ('ypghd.ocqvp@yahoo.com','fuel oil');
INSERT INTO UtilityType (Email, UtilityType) values ('wrebxlyza.zilvomjtr@yahoo.com','steam');
INSERT INTO UtilityType (Email, UtilityType) values ('edbsgqp.lsnofunj@hotmail.com','fuel oil');
INSERT INTO UtilityType (Email, UtilityType) values ('fntafhzqe.uhexacvsog@hotmail.com','steam');
INSERT INTO UtilityType (Email, UtilityType) values ('gsbyss.jlcghlrgtv@gmail.com','off-the-grid');
INSERT INTO UtilityType (Email, UtilityType) values ('lofdibmw.yhhrztbqcd@hotmail.com','gas');
INSERT INTO UtilityType (Email, UtilityType) values ('sbipn.kuqoihyvun@yahoo.com','off-the-grid');
INSERT INTO UtilityType (Email, UtilityType) values ('kyqzwjq.qgtxlhlz@outlook.com','gas');
INSERT INTO UtilityType (Email, UtilityType) values ('wattdc.kpwmzbip@yahoo.com','steam');
INSERT INTO UtilityType (Email, UtilityType) values ('qasge.vkwhx@yahoo.com','steam');
INSERT INTO UtilityType (Email, UtilityType) values ('zilqrs.onvmnl@gmail.com','gas');
INSERT INTO UtilityType (Email, UtilityType) values ('diztbfzr.vqbzb@gmail.com','electric');
INSERT INTO UtilityType (Email, UtilityType) values ('dmemwafc.mxoacset@yahoo.com','off-the-grid');
INSERT INTO UtilityType (Email, UtilityType) values ('dozaxk.snrqcadfr@hotmail.com','steam');
INSERT INTO UtilityType (Email, UtilityType) values ('bwcrbvt.pmsfqbwo@hotmail.com','steam');
INSERT INTO UtilityType (Email, UtilityType) values ('squsr.ariepax@outlook.com','off-the-grid');
