INSERT INTO WaterHeater (ApplianceId, Email, Capacity, Temperature, EnergySource) values (1,'mktxyyfbjl.kbqhrkxej@gmail.com', 60.6, 75,'gas');
INSERT INTO WaterHeater (ApplianceId, Email, Capacity, Temperature, EnergySource) values (1,'zxdphvm.bnflhn@hotmail.com', 48.7, 67,'gas');
INSERT INTO WaterHeater (ApplianceId, Email, Capacity, Temperature, EnergySource) values (1,'khvxmd.lanqe@gmail.com', 27.0, 67,'thermosolar');
INSERT INTO WaterHeater (ApplianceId, Email, Capacity, Temperature, EnergySource) values (1,'urstm.lyrgcnn@gmail.com', 31.4, 80,'gas');
INSERT INTO WaterHeater (ApplianceId, Email, Capacity, Temperature, EnergySource) values (1,'spsmxyozhq.qywtidufjz@gmail.com', 68.1, 67,'heat pump');
INSERT INTO WaterHeater (ApplianceId, Email, Capacity, Temperature, EnergySource) values (1,'ccxezue.wuxtawu@gmail.com', 49.6, 80,'heat pump');
INSERT INTO WaterHeater (ApplianceId, Email, Capacity, Temperature, EnergySource) values (1,'giodplp.hvmwyh@outlook.com', 63.5, 74,'gas');
INSERT INTO WaterHeater (ApplianceId, Email, Capacity, Temperature, EnergySource) values (1,'xcwfvut.kamua@gmail.com', 41.3, 80,'thermosolar');
INSERT INTO WaterHeater (ApplianceId, Email, Capacity, Temperature, EnergySource) values (1,'yybzp.ohldcewgzs@outlook.com', 45.8, 72,'thermosolar');
INSERT INTO WaterHeater (ApplianceId, Email, Capacity, Temperature, EnergySource) values (1,'iyyol.glujl@gmail.com', 64.1, 71,'electric');
INSERT INTO WaterHeater (ApplianceId, Email, Capacity, Temperature, EnergySource) values (1,'dygzz.gqehriguo@hotmail.com', 68.7, 74,'thermosolar');
INSERT INTO WaterHeater (ApplianceId, Email, Capacity, Temperature, EnergySource) values (1,'jkmoj.anlzli@gmail.com', 26.6, 71,'electric');
INSERT INTO WaterHeater (ApplianceId, Email, Capacity, Temperature, EnergySource) values (1,'dbbxdtzqn.qioarzw@hotmail.com', 78.0, 68,'thermosolar');
INSERT INTO WaterHeater (ApplianceId, Email, Capacity, Temperature, EnergySource) values (1,'qimlly.xxnejproek@hotmail.com', 57.9, 74,'thermosolar');
INSERT INTO WaterHeater (ApplianceId, Email, Capacity, Temperature, EnergySource) values (1,'tclplxspg.ertff@gmail.com', 26.9, 74,'gas');
INSERT INTO WaterHeater (ApplianceId, Email, Capacity, Temperature, EnergySource) values (1,'nvxofsr.hcrpv@yahoo.com', 32.9, 76,'thermosolar');
INSERT INTO WaterHeater (ApplianceId, Email, Capacity, Temperature, EnergySource) values (1,'sbipn.kuqoihyvun@yahoo.com', 65.9, 65,'gas');
INSERT INTO WaterHeater (ApplianceId, Email, Capacity, Temperature, EnergySource) values (1,'wattdc.kpwmzbip@yahoo.com', 52.4, 77,'gas');
INSERT INTO WaterHeater (ApplianceId, Email, Capacity, Temperature, EnergySource) values (1,'zilqrs.onvmnl@gmail.com', 72.4, 70,'heat pump');
INSERT INTO WaterHeater (ApplianceId, Email, Capacity, Temperature, EnergySource) values (1,'squsr.ariepax@outlook.com', 55.1, 75,'gas');
