INSERT INTO Heater (ApplianceId, Email, HeaterEnergySource) values (1,'ahqejl.csewbslre@outlook.com','gas');
INSERT INTO Heater (ApplianceId, Email, HeaterEnergySource) values (1,'wvakphra.qdrgftpkk@outlook.com','electric');
INSERT INTO Heater (ApplianceId, Email, HeaterEnergySource) values (1,'asjpka.rcklxq@outlook.com','electric');
INSERT INTO Heater (ApplianceId, Email, HeaterEnergySource) values (1,'cpixuxabd.qpdbx@gmail.com','fuel oil');
INSERT INTO Heater (ApplianceId, Email, HeaterEnergySource) values (1,'eokjewvo.rolhepl@hotmail.com','electric');
INSERT INTO Heater (ApplianceId, Email, HeaterEnergySource) values (1,'ovgjn.pngew@outlook.com','electric');
INSERT INTO Heater (ApplianceId, Email, HeaterEnergySource) values (1,'kcovojowh.wjybftve@gmail.com','fuel oil');
INSERT INTO Heater (ApplianceId, Email, HeaterEnergySource) values (1,'epjnhjif.pfbncwh@hotmail.com','gas');
INSERT INTO Heater (ApplianceId, Email, HeaterEnergySource) values (1,'nsarfibcoq.sttulj@outlook.com','gas');
INSERT INTO Heater (ApplianceId, Email, HeaterEnergySource) values (1,'djttpsh.nnizif@gmail.com','fuel oil');
INSERT INTO Heater (ApplianceId, Email, HeaterEnergySource) values (1,'pnlreotd.gycaxkvmvo@hotmail.com','gas');
INSERT INTO Heater (ApplianceId, Email, HeaterEnergySource) values (1,'klcnkuqwk.ufazrl@outlook.com','electric');
INSERT INTO Heater (ApplianceId, Email, HeaterEnergySource) values (1,'pjnpi.tohfvsn@outlook.com','gas');
INSERT INTO Heater (ApplianceId, Email, HeaterEnergySource) values (1,'bmfxvqf.dyewekj@outlook.com','fuel oil');
INSERT INTO Heater (ApplianceId, Email, HeaterEnergySource) values (1,'pywvpw.tbgml@outlook.com','electric');
INSERT INTO Heater (ApplianceId, Email, HeaterEnergySource) values (1,'zwqthuc.xhrjzxwr@hotmail.com','electric');
INSERT INTO Heater (ApplianceId, Email, HeaterEnergySource) values (1,'itewtwyzw.qdvpfx@outlook.com','gas');
INSERT INTO Heater (ApplianceId, Email, HeaterEnergySource) values (1,'mmwraelwm.uvjrsp@outlook.com','fuel oil');
INSERT INTO Heater (ApplianceId, Email, HeaterEnergySource) values (1,'gulsthcn.nhabzdc@yahoo.com','electric');
INSERT INTO Heater (ApplianceId, Email, HeaterEnergySource) values (1,'eynkd.ounorracj@outlook.com','fuel oil');
INSERT INTO Heater (ApplianceId, Email, HeaterEnergySource) values (1,'kpcfrihokc.rdaqylsjlm@gmail.com','electric');
INSERT INTO Heater (ApplianceId, Email, HeaterEnergySource) values (1,'opqsbcms.unwlrcpka@hotmail.com','electric');
INSERT INTO Heater (ApplianceId, Email, HeaterEnergySource) values (1,'agsciy.yorxv@outlook.com','electric');
INSERT INTO Heater (ApplianceId, Email, HeaterEnergySource) values (1,'zplewtkzdi.hhanyrxh@hotmail.com','fuel oil');
INSERT INTO Heater (ApplianceId, Email, HeaterEnergySource) values (1,'fgaenbx.tirfmblwmb@outlook.com','fuel oil');
INSERT INTO Heater (ApplianceId, Email, HeaterEnergySource) values (1,'fbjnjj.jnhcfp@outlook.com','electric');
INSERT INTO Heater (ApplianceId, Email, HeaterEnergySource) values (1,'qasge.vkwhx@yahoo.com','electric');
INSERT INTO Heater (ApplianceId, Email, HeaterEnergySource) values (1,'dmemwafc.mxoacset@yahoo.com','electric');
INSERT INTO Heater (ApplianceId, Email, HeaterEnergySource) values (1,'dozaxk.snrqcadfr@hotmail.com','fuel oil');
