-- Insert 100 household data
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('xhzkzad.sckkst@outlook.com','16627', 56011,'mobile home',68,NULL);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('ahqejl.csewbslre@outlook.com','17271', 96670,'condominium',72,73);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('fryjjhrez.gnltrdvumm@yahoo.com','83525', 44751,'mobile home',66,79);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('ndpipmp.bjkjk@gmail.com','38614', 22034,'townhome',71,80);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('rhwgp.bhvpfe@outlook.com','75951', 30352,'mobile home',71,74);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('vlcojiy.fwdjtczp@yahoo.com','23922', 83086,'apartment',73,71);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('vsgbgdl.tgftnz@gmail.com','98382', 81491,'house',73,80);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('dhhilddh.yudnpois@yahoo.com','15730', 62596,'apartment',75,NULL);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('wvakphra.qdrgftpkk@outlook.com','27217', 37282,'condominium',NULL,NULL);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('asjpka.rcklxq@outlook.com','65784', 76499,'house',NULL,NULL);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('pytpnqms.dtsnein@outlook.com','98953', 50374,'house',74,76);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('wnegrv.calkded@yahoo.com','28442', 93969,'townhome',69,80);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('cpixuxabd.qpdbx@gmail.com','4338', 46770,'condominium',72,79);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('eokjewvo.rolhepl@hotmail.com','96728', 55876,'condominium',71,79);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('mktxyyfbjl.kbqhrkxej@gmail.com','11499', 32031,'apartment',73,NULL);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('zxdphvm.bnflhn@hotmail.com','56080', 51119,'townhome',67,74);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('tmfcqvwei.eccrlwui@yahoo.com','29734', 82367,'mobile home',NULL,NULL);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('ovgjn.pngew@outlook.com','22714', 75440,'house',73,74);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('grmngou.wrgrbsbmey@hotmail.com','18461', 5322,'townhome',NULL,NULL);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('itdzt.kjrhulh@outlook.com','94562', 77501,'mobile home',68,79);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('unzqoq.fjhopwiee@outlook.com','54466', 13567,'condominium',74,70);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('khvxmd.lanqe@gmail.com','48867', 11432,'mobile home',67,NULL);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('urstm.lyrgcnn@gmail.com','62446', 11980,'townhome',65,79);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('hjypic.agcbb@outlook.com','97366', 54032,'condominium',72,74);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('fqeshxgx.llblpd@gmail.com','84530', 58028,'house',NULL,NULL);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('spsmxyozhq.qywtidufjz@gmail.com','28043', 41447,'house',74,70);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('mdreacz.ejbkihgmkw@outlook.com','81226', 45457,'condominium',68,78);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('zzzdt.zaxsxftzxv@gmail.com','67058', 42239,'mobile home',NULL,NULL);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('erlmfpw.gvmypognpu@hotmail.com','20580', 54896,'townhome',71,NULL);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('ccxezue.wuxtawu@gmail.com','13834', 67246,'apartment',70,73);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('kcovojowh.wjybftve@gmail.com','75680', 59492,'mobile home',66,70);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('pyetbtyxu.bnsgiajmkz@hotmail.com','50321', 30865,'house',65,80);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('giodplp.hvmwyh@outlook.com','19179', 72628,'condominium',NULL,NULL);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('xcwfvut.kamua@gmail.com','28409', 87968,'townhome',68,78);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('iolqf.bfwtgsze@yahoo.com','79841', 44738,'condominium',74,76);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('aqtluaij.tpcqmk@outlook.com','24872', 90477,'apartment',66,NULL);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('uwvdpz.tvmjsi@outlook.com','72033', 74355,'house',NULL,NULL);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('yybzp.ohldcewgzs@outlook.com','95959', 6237,'house',66,80);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('epjnhjif.pfbncwh@hotmail.com','21241', 48345,'house',75,76);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('nsarfibcoq.sttulj@outlook.com','52336', 49196,'apartment',67,76);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('djttpsh.nnizif@gmail.com','90421', 56138,'house',NULL,NULL);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('bgfruxt.bzxaqn@yahoo.com','29048', 94705,'house',75,77);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('pnlreotd.gycaxkvmvo@hotmail.com','22989', 34324,'condominium',65,NULL);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('srzwkfjyo.hgotns@gmail.com','66945', 18358,'house',69,80);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('ufnerjhy.lplqrstry@yahoo.com','57059', 66719,'apartment',75,76);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('klcnkuqwk.ufazrl@outlook.com','15233', 81405,'house',NULL,NULL);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('jorce.jcrvnderk@yahoo.com','32359', 13878,'apartment',68,76);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('pjnpi.tohfvsn@outlook.com','28055', 83495,'house',67,80);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('iyyol.glujl@gmail.com','71929', 25168,'condominium',NULL,NULL);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('bmfxvqf.dyewekj@outlook.com','33834', 54716,'house',71,NULL);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('smpwu.gibhncer@hotmail.com','92885', 67769,'house',68,77);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('dygzz.gqehriguo@hotmail.com','15379', 80596,'townhome',65,76);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('xzwstkiibr.clxbqwvvm@yahoo.com','67491', 48558,'mobile home',72,72);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('pywvpw.tbgml@outlook.com','88539', 36124,'mobile home',75,70);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('ptcmpco.jnqalia@outlook.com','82839', 1708,'mobile home',NULL,NULL);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('zwqthuc.xhrjzxwr@hotmail.com','75462', 44470,'apartment',73,71);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('uralvthzi.jyjhohvvdg@gmail.com','64840', 32485,'mobile home',69,NULL);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('sjosrgks.qbdwuqmjl@outlook.com','97405', 42009,'townhome',65,71);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('ndmqxhli.wlaypuawv@gmail.com','70522', 19529,'condominium',68,79);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('itewtwyzw.qdvpfx@outlook.com','62058', 56809,'house',75,78);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('mmwraelwm.uvjrsp@outlook.com','42323', 92017,'house',71,73);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('zttqvvo.nxcxor@outlook.com','86434', 12897,'condominium',70,79);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('hvbac.jzcla@hotmail.com','8863', 37458,'mobile home',65,76);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('tcgjbbv.tybrggdl@gmail.com','25028', 41322,'mobile home',73,NULL);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('gulsthcn.nhabzdc@yahoo.com','44040', 43407,'house',NULL,NULL);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('jkmoj.anlzli@gmail.com','90607', 41888,'townhome',72,78);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('bkbio.yghhi@hotmail.com','27892', 24608,'condominium',66,74);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('mxqfsbzvhq.pmdfz@outlook.com','39328', 19256,'house',71,76);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('nxabsvdx.lseiew@hotmail.com','28366', 43410,'townhome',72,74);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('dbbxdtzqn.qioarzw@hotmail.com','83276', 46316,'house',67,76);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('dwszhdtxk.hcpjjbcc@gmail.com','11819', 36132,'condominium',65,NULL);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('eynkd.ounorracj@outlook.com','52738', 65846,'mobile home',70,80);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('mgpbl.jfkwks@outlook.com','4743', 3248,'townhome',NULL,NULL);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('vnqfmfpja.lodgygnunm@outlook.com','20624', 39581,'house',67,76);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('kpcfrihokc.rdaqylsjlm@gmail.com','45140', 64325,'townhome',66,80);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('qimlly.xxnejproek@hotmail.com','75189', 71464,'house',73,70);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('opqsbcms.unwlrcpka@hotmail.com','85317', 17877,'condominium',70,80);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('agsciy.yorxv@outlook.com','68450', 28741,'apartment',69,NULL);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('znnjjutr.gnnmt@yahoo.com','47840', 67228,'townhome',74,80);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('zplewtkzdi.hhanyrxh@hotmail.com','57059', 69499,'townhome',68,74);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('tclplxspg.ertff@gmail.com','31772', 58347,'apartment',NULL,NULL);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('nvxofsr.hcrpv@yahoo.com','48265', 35659,'townhome',NULL,NULL);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('fgaenbx.tirfmblwmb@outlook.com','37243', 90415,'mobile home',72,78);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('fbjnjj.jnhcfp@outlook.com','99319', 83521,'house',68,73);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('ypghd.ocqvp@yahoo.com','44082', 27651,'apartment',73,NULL);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('wrebxlyza.zilvomjtr@yahoo.com','73458', 20973,'condominium',67,73);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('edbsgqp.lsnofunj@hotmail.com','15723', 49612,'condominium',72,80);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('fntafhzqe.uhexacvsog@hotmail.com','30133', 76811,'townhome',74,71);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('gsbyss.jlcghlrgtv@gmail.com','4736', 64113,'apartment',NULL,NULL);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('lofdibmw.yhhrztbqcd@hotmail.com','3452', 87797,'apartment',66,78);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('sbipn.kuqoihyvun@yahoo.com','33445', 20829,'apartment',NULL,NULL);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('kyqzwjq.qgtxlhlz@outlook.com','76716', 44450,'townhome',67,NULL);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('wattdc.kpwmzbip@yahoo.com','21606', 34629,'house',73,70);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('qasge.vkwhx@yahoo.com','17815', 59857,'mobile home',75,80);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('zilqrs.onvmnl@gmail.com','27559', 50800,'townhome',75,70);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('diztbfzr.vqbzb@gmail.com','49548', 20688,'condominium',68,74);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('dmemwafc.mxoacset@yahoo.com','21401', 56179,'townhome',NULL,NULL);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('dozaxk.snrqcadfr@hotmail.com','73737', 94490,'apartment',74,75);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('bwcrbvt.pmsfqbwo@hotmail.com','31008', 44197,'house',75,NULL);
INSERT INTO HouseHold (Email, PostalCode, HouseSize, HouseType, CoolingThermostatTemp, HeatingThermostatTemp) values ('squsr.ariepax@outlook.com','32160', 78784,'mobile home',NULL,NULL);
